import type { GalaxyConfig, GalaxyGroupInfo } from '../../types/universe';

// ============================================================================
// COSMIC GALAXY GROUPS DEFINITION (see full registry below — groups are
// declared after all galaxy configs to include the IC 1579 special galaxy)
// ============================================================================

// ============================================================================
// GROUP A: LOCAL CLUSTER (Galaxies 01, 03, 07, 10)
// ============================================================================
export const GALAXY_01_CONFIG: GalaxyConfig = {
  id: 'galaxy01',
  name: 'Aether Prime',
  subtitle: 'Grand-Design Barred Spiral',
  description: 'Grand-design barred spiral with cyan-blue relativistic ion streams and emerald outer dust halo (Reference Quality Baseline).',
  type: 'barred-spiral',
  groupId: 'groupA',
  position: [0, 0, 0],
  rotation: [0.08, 0, 0],
  scale: 1.0,
  speed: 0.28,
  turbulence: 0.8,
  boundingRadius: 42.0,
  hasBlackHole: false,
  palette: {
    core: '#FFF8FF',
    coreHalo: '#A8F0FF',
    inner: '#22B3E0',
    deep: '#0B5394',
    armsPrimary: '#FF75C8',
    armsSecondary: '#D75CFF',
    armsTertiary: '#8B55FF',
    dust: '#0F6B4F',
    dustSecondary: '#1E9080',
    starFormation: '#FF7B30',
    starFormationWarm: '#FFB347',
    ambientStars: ['#FFFFFF', '#7EC8E3', '#FF6B6B'],
  },
  morphology: {
    type: 'barred-spiral',
    armCount: 2,
    asymmetry: 0.2,
    barStrength: 0.8,
    ringStrength: 0.0,
    diskFlattening: 0.65,
    coreDensity: 1.0,
    dustDensity: 0.8,
    verticalThickness: 1.0,
    starFormationDensity: 1.0,
    spiralTightness: 3.2,
  },
};

export const GALAXY_03_CONFIG: GalaxyConfig = {
  id: 'galaxy03',
  name: 'Verdant',
  subtitle: 'Emerald Deep Multi-Arm',
  description: 'Deep volumetric emerald spiral with 3 major arms, layered dark green dust, and a living teal supermassive black hole.',
  type: 'emerald-multi-arm',
  groupId: 'groupA',
  position: [-135, 18, -80],
  rotation: [0.18, -0.35, -0.12],
  scale: 1.1,
  speed: 0.26,
  turbulence: 0.85,
  boundingRadius: 46.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.05,
    photonRingRadius: 1.55,
    accretionInnerRadius: 1.7,
    accretionOuterRadius: 8.2,
    diskTilt: [-0.2, 0.3, 0.1],
    rotationSpeed: 2.1,
    infallRate: 1.35,
    turbulence: 0.85,
    lensingStrength: 1.1,
    palette: {
      horizonRim: '#D8FFE8',
      photonRing: '#F5FFF8',
      accretionInner: '#8FFFC1',
      accretionMid: '#28C7A5',
      accretionOuter: '#075C3D',
      infallStream: '#A7FF5A',
    },
  },
  palette: {
    core: '#F5FFF8',
    coreHalo: '#D8FFE8',
    inner: '#8FFFC1',
    deep: '#28C7A5',
    armsPrimary: '#0FA66B',
    armsSecondary: '#075C3D',
    armsTertiary: '#063B2A',
    dust: '#04281C',
    dustSecondary: '#0E4E38',
    starFormation: '#A7FF5A',
    starFormationWarm: '#E7FFB0',
    ambientStars: ['#D8FFE8', '#8FFFC1', '#55FFD0'],
  },
  morphology: {
    type: 'emerald-multi-arm',
    armCount: 3,
    asymmetry: 0.45,
    barStrength: 0.2,
    ringStrength: 0.3,
    diskFlattening: 0.45,
    coreDensity: 1.1,
    dustDensity: 1.3,
    verticalThickness: 1.6,
    starFormationDensity: 1.4,
    spiralTightness: 3.8,
  },
};

export const GALAXY_07_CONFIG: GalaxyConfig = {
  id: 'galaxy07',
  name: 'Aethelgard',
  subtitle: 'Violet / Indigo Dual Spiral',
  description: 'Two luminous violet spiral arms crossing deep indigo dust channels with glowing ultraviolet star-forming clusters.',
  type: 'barred-spiral',
  groupId: 'groupA',
  position: [-90, -32, -45],
  rotation: [-0.15, 0.22, 0.35],
  scale: 1.02,
  speed: 0.29,
  turbulence: 0.82,
  boundingRadius: 44.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.0,
    photonRingRadius: 1.5,
    accretionInnerRadius: 1.65,
    accretionOuterRadius: 7.8,
    diskTilt: [0.25, -0.15, 0.3],
    rotationSpeed: 2.0,
    infallRate: 1.3,
    turbulence: 0.88,
    lensingStrength: 1.05,
    palette: {
      horizonRim: '#C084FC',
      photonRing: '#F5F0FF',
      accretionInner: '#A78BFA',
      accretionMid: '#8B5CF6',
      accretionOuter: '#4F46E5',
      infallStream: '#C084FC',
    },
  },
  palette: {
    core: '#F5F0FF',
    coreHalo: '#C084FC',
    inner: '#A78BFA',
    deep: '#8B5CF6',
    armsPrimary: '#8B5CF6',
    armsSecondary: '#4F46E5',
    armsTertiary: '#1E1B4B',
    dust: '#0F0E2A',
    dustSecondary: '#1E1B4B',
    starFormation: '#C084FC',
    starFormationWarm: '#E9D5FF',
    ambientStars: ['#F5F0FF', '#C084FC', '#818CF8'],
  },
  morphology: {
    type: 'barred-spiral',
    armCount: 2,
    asymmetry: 0.35,
    barStrength: 0.4,
    ringStrength: 0.1,
    diskFlattening: 0.6,
    coreDensity: 1.15,
    dustDensity: 1.2,
    verticalThickness: 1.25,
    starFormationDensity: 1.3,
    spiralTightness: 3.4,
  },
};

export const GALAXY_10_CONFIG: GalaxyConfig = {
  id: 'galaxy10',
  name: 'Chrono Forge',
  subtitle: 'Amber / Copper Elliptical Spiral',
  description: 'Dense elliptical spiral with heavy copper dust lanes, bright compact core, and a thick golden-bronze halo.',
  type: 'dense-elliptical',
  groupId: 'groupA',
  position: [-50, -48, 65],
  rotation: [0.3, 0.1, -0.2],
  scale: 1.06,
  speed: 0.25,
  turbulence: 0.78,
  boundingRadius: 43.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.1,
    photonRingRadius: 1.58,
    accretionInnerRadius: 1.75,
    accretionOuterRadius: 8.0,
    diskTilt: [-0.3, 0.2, 0.1],
    rotationSpeed: 1.9,
    infallRate: 1.2,
    turbulence: 0.8,
    lensingStrength: 1.1,
    palette: {
      horizonRim: '#FFE7A3',
      photonRing: '#FFF8E7',
      accretionInner: '#F59E0B',
      accretionMid: '#B45309',
      accretionOuter: '#78350F',
      infallStream: '#F59E0B',
    },
  },
  palette: {
    core: '#FFF8E7',
    coreHalo: '#FFE7A3',
    inner: '#F59E0B',
    deep: '#B45309',
    armsPrimary: '#B45309',
    armsSecondary: '#78350F',
    armsTertiary: '#271405',
    dust: '#1A0C02',
    dustSecondary: '#271405',
    starFormation: '#FBBF24',
    starFormationWarm: '#FDE68A',
    ambientStars: ['#FFF8E7', '#FDE68A', '#F59E0B'],
  },
  morphology: {
    type: 'dense-elliptical',
    armCount: 2,
    asymmetry: 0.2,
    barStrength: 0.3,
    ringStrength: 0.5,
    diskFlattening: 0.7,
    coreDensity: 1.4,
    dustDensity: 1.3,
    verticalThickness: 1.5,
    starFormationDensity: 1.1,
    spiralTightness: 3.1,
  },
};

// ============================================================================
// GROUP B: SOUTHERN STREAM (Galaxies 02, 05, 08, 13)
// ============================================================================
export const GALAXY_02_CONFIG: GalaxyConfig = {
  id: 'galaxy02',
  name: 'Ignis Vesper',
  subtitle: 'Flocculent Ring • Golden Singularity',
  description: 'Asymmetric ringed flocculent spiral hosting a supermassive black hole with warm golden accretion disk and deep burgundy dust.',
  type: 'flocculent-ring',
  groupId: 'groupB',
  position: [185, -15, 210],
  rotation: [-0.25, 0.45, 0.15],
  scale: 1.05,
  speed: 0.32,
  turbulence: 0.95,
  boundingRadius: 45.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 0.95,
    photonRingRadius: 1.45,
    accretionInnerRadius: 1.6,
    accretionOuterRadius: 7.5,
    diskTilt: [0.35, 0.15, -0.2],
    rotationSpeed: 1.8,
    infallRate: 1.2,
    turbulence: 0.9,
    lensingStrength: 1.0,
    palette: {
      horizonRim: '#FFD27A',
      photonRing: '#FFF4D6',
      accretionInner: '#FFB84D',
      accretionMid: '#C45A17',
      accretionOuter: '#7F1D1D',
      infallStream: '#FF5E78',
    },
  },
  palette: {
    core: '#FFF4D6',
    coreHalo: '#FFD27A',
    inner: '#FFB84D',
    deep: '#C45A17',
    armsPrimary: '#D946EF',
    armsSecondary: '#8B5CF6',
    armsTertiary: '#4C1D95',
    dust: '#7F1D1D',
    dustSecondary: '#581C1C',
    starFormation: '#FF5E78',
    starFormationWarm: '#FFD166',
    ambientStars: ['#FFF4D6', '#D8B4FE', '#FFB4A2'],
  },
  morphology: {
    type: 'flocculent-ring',
    armCount: 3,
    asymmetry: 0.65,
    barStrength: 0.0,
    ringStrength: 0.7,
    diskFlattening: 0.55,
    coreDensity: 0.8,
    dustDensity: 1.1,
    verticalThickness: 1.35,
    starFormationDensity: 1.25,
    spiralTightness: 3.6,
  },
};

export const GALAXY_05_CONFIG: GalaxyConfig = {
  id: 'galaxy05',
  name: 'Red Veil',
  subtitle: 'Turbulent Crimson • Plasma Tempest',
  description: 'Dynamically unstable dark crimson galaxy with 2 dominant arms and a violently active red/orange supermassive black hole.',
  type: 'turbulent-crimson',
  groupId: 'groupB',
  position: [95, -25, 90],
  rotation: [-0.3, -0.15, 0.25],
  scale: 1.1,
  speed: 0.38,
  turbulence: 1.15,
  boundingRadius: 47.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.10,
    photonRingRadius: 1.60,
    accretionInnerRadius: 1.75,
    accretionOuterRadius: 8.5,
    diskTilt: [-0.35, -0.15, 0.45],
    rotationSpeed: 2.6,
    infallRate: 1.6,
    turbulence: 1.25,
    lensingStrength: 1.25,
    palette: {
      horizonRim: '#FF9E2C',
      photonRing: '#FFF1DC',
      accretionInner: '#FF6B1A',
      accretionMid: '#FF304F',
      accretionOuter: '#56000D',
      infallStream: '#FF304F',
    },
  },
  palette: {
    core: '#FFF1DC',
    coreHalo: '#FF9E2C',
    inner: '#FF6B1A',
    deep: '#FF304F',
    armsPrimary: '#D71932',
    armsSecondary: '#9E1020',
    armsTertiary: '#56000D',
    dust: '#260006',
    dustSecondary: '#090000',
    starFormation: '#FF304F',
    starFormationWarm: '#FF6B1A',
    ambientStars: ['#FFF1DC', '#FF6B1A', '#FF304F'],
  },
  morphology: {
    type: 'turbulent-crimson',
    armCount: 3,
    asymmetry: 0.75,
    barStrength: 0.3,
    ringStrength: 0.2,
    diskFlattening: 0.5,
    coreDensity: 1.2,
    dustDensity: 1.35,
    verticalThickness: 1.45,
    starFormationDensity: 1.5,
    spiralTightness: 3.5,
  },
};

export const GALAXY_08_CONFIG: GalaxyConfig = {
  id: 'galaxy08',
  name: 'Aquila',
  subtitle: 'Turquoise / Aqua Ringed Spiral',
  description: 'Ringed spiral with multiple inner streams, thick vertical gas structure, and luminous turquoise starburst clusters.',
  type: 'ring-spiral',
  groupId: 'groupB',
  position: [220, 24, 140],
  rotation: [0.15, -0.3, 0.12],
  scale: 1.08,
  speed: 0.31,
  turbulence: 0.9,
  boundingRadius: 45.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.02,
    photonRingRadius: 1.52,
    accretionInnerRadius: 1.68,
    accretionOuterRadius: 7.9,
    diskTilt: [0.1, 0.35, -0.15],
    rotationSpeed: 2.1,
    infallRate: 1.3,
    turbulence: 0.85,
    lensingStrength: 1.1,
    palette: {
      horizonRim: '#BFFBFF',
      photonRing: '#F0FFFF',
      accretionInner: '#67E8F9',
      accretionMid: '#22D3EE',
      accretionOuter: '#064E5A',
      infallStream: '#14B8A6',
    },
  },
  palette: {
    core: '#F0FFFF',
    coreHalo: '#BFFBFF',
    inner: '#67E8F9',
    deep: '#22D3EE',
    armsPrimary: '#14B8A6',
    armsSecondary: '#0891B2',
    armsTertiary: '#064E5A',
    dust: '#022C33',
    dustSecondary: '#064E5A',
    starFormation: '#22D3EE',
    starFormationWarm: '#A5F3FC',
    ambientStars: ['#F0FFFF', '#67E8F9', '#14B8A6'],
  },
  morphology: {
    type: 'ring-spiral',
    armCount: 2,
    asymmetry: 0.4,
    barStrength: 0.1,
    ringStrength: 0.75,
    diskFlattening: 0.52,
    coreDensity: 1.1,
    dustDensity: 1.2,
    verticalThickness: 1.4,
    starFormationDensity: 1.35,
    spiralTightness: 3.5,
  },
};

export const GALAXY_13_CONFIG: GalaxyConfig = {
  id: 'galaxy13',
  name: 'Solaris',
  subtitle: 'Pink / Coral Orange Ring Spiral',
  description: 'Luminous ring spiral with bright peach inner disk, fragmented outer dust, and dense coral star-forming knots.',
  type: 'ring-spiral',
  groupId: 'groupB',
  position: [140, -45, 270],
  rotation: [-0.2, 0.18, 0.4],
  scale: 1.04,
  speed: 0.33,
  turbulence: 0.92,
  boundingRadius: 44.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 0.98,
    photonRingRadius: 1.48,
    accretionInnerRadius: 1.62,
    accretionOuterRadius: 7.6,
    diskTilt: [-0.2, -0.3, 0.15],
    rotationSpeed: 2.2,
    infallRate: 1.35,
    turbulence: 0.9,
    lensingStrength: 1.08,
    palette: {
      horizonRim: '#FDBA74',
      photonRing: '#FFF7ED',
      accretionInner: '#FB923C',
      accretionMid: '#FB7185',
      accretionOuter: '#4C0519',
      infallStream: '#F472B6',
    },
  },
  palette: {
    core: '#FFF7ED',
    coreHalo: '#FDBA74',
    inner: '#FB923C',
    deep: '#FB7185',
    armsPrimary: '#F472B6',
    armsSecondary: '#E11D48',
    armsTertiary: '#4C0519',
    dust: '#26000B',
    dustSecondary: '#4C0519',
    starFormation: '#FB7185',
    starFormationWarm: '#FED7AA',
    ambientStars: ['#FFF7ED', '#FDBA74', '#F472B6'],
  },
  morphology: {
    type: 'ring-spiral',
    armCount: 3,
    asymmetry: 0.5,
    barStrength: 0.2,
    ringStrength: 0.65,
    diskFlattening: 0.58,
    coreDensity: 1.2,
    dustDensity: 1.15,
    verticalThickness: 1.3,
    starFormationDensity: 1.3,
    spiralTightness: 3.3,
  },
};

// ============================================================================
// GROUP C: ABYSSAL RIDGE (Galaxies 04, 09, 12, 15)
// ============================================================================
export const GALAXY_04_CONFIG: GalaxyConfig = {
  id: 'galaxy04',
  name: 'Eclipse',
  subtitle: 'Golden Eclipse • Relativistic Horizon',
  description: 'Ancient thick barred spiral featuring an elongated golden bar, high-contrast black dust voids, and an intense amber supermassive black hole.',
  type: 'golden-dark-barred',
  groupId: 'groupC',
  position: [-45, 42, -210],
  rotation: [0.35, 0.2, -0.4],
  scale: 1.15,
  speed: 0.34,
  turbulence: 0.9,
  boundingRadius: 48.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.15,
    photonRingRadius: 1.65,
    accretionInnerRadius: 1.8,
    accretionOuterRadius: 9.0,
    diskTilt: [0.4, -0.25, 0.3],
    rotationSpeed: 2.4,
    infallRate: 1.5,
    turbulence: 1.0,
    lensingStrength: 1.2,
    palette: {
      horizonRim: '#FFD966',
      photonRing: '#FFF4C2',
      accretionInner: '#F2C94C',
      accretionMid: '#C69214',
      accretionOuter: '#3A2108',
      infallStream: '#FFAE33',
    },
  },
  palette: {
    core: '#FFF4C2',
    coreHalo: '#FFD966',
    inner: '#F2C94C',
    deep: '#C69214',
    armsPrimary: '#FF9F1C',
    armsSecondary: '#76500B',
    armsTertiary: '#3A2108',
    dust: '#020202',
    dustSecondary: '#140C04',
    starFormation: '#FFD966',
    starFormationWarm: '#FFAE33',
    ambientStars: ['#FFF4C2', '#F2C94C', '#FF9F1C'],
  },
  morphology: {
    type: 'golden-dark-barred',
    armCount: 2,
    asymmetry: 0.55,
    barStrength: 1.1,
    ringStrength: 0.0,
    diskFlattening: 0.6,
    coreDensity: 1.3,
    dustDensity: 1.25,
    verticalThickness: 1.2,
    starFormationDensity: 1.1,
    spiralTightness: 3.0,
    darkLaneStrength: 1.4,
    voidStrength: 0.8,
  },
};

export const GALAXY_09_CONFIG: GalaxyConfig = {
  id: 'galaxy09',
  name: 'Siren',
  subtitle: 'Magenta / Blue Flocculent Spiral',
  description: 'Asymmetric flocculent spiral with patchy magenta and blue starburst knots emerging from deep violet clouds.',
  type: 'flocculent-asymmetric',
  groupId: 'groupC',
  position: [-140, 65, -290],
  rotation: [-0.35, 0.15, -0.25],
  scale: 1.08,
  speed: 0.35,
  turbulence: 1.1,
  boundingRadius: 46.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.05,
    photonRingRadius: 1.55,
    accretionInnerRadius: 1.7,
    accretionOuterRadius: 8.2,
    diskTilt: [0.3, 0.2, -0.4],
    rotationSpeed: 2.3,
    infallRate: 1.4,
    turbulence: 1.05,
    lensingStrength: 1.15,
    palette: {
      horizonRim: '#F9A8D4',
      photonRing: '#FFF5FF',
      accretionInner: '#EC4899',
      accretionMid: '#A855F7',
      accretionOuter: '#1E1B4B',
      infallStream: '#3B82F6',
    },
  },
  palette: {
    core: '#FFF5FF',
    coreHalo: '#F9A8D4',
    inner: '#EC4899',
    deep: '#A855F7',
    armsPrimary: '#3B82F6',
    armsSecondary: '#6366F1',
    armsTertiary: '#1E1B4B',
    dust: '#0B0920',
    dustSecondary: '#1E1B4B',
    starFormation: '#EC4899',
    starFormationWarm: '#FBCFE8',
    ambientStars: ['#FFF5FF', '#F9A8D4', '#60A5FA'],
  },
  morphology: {
    type: 'flocculent-asymmetric',
    armCount: 3,
    asymmetry: 0.8,
    barStrength: 0.1,
    ringStrength: 0.2,
    diskFlattening: 0.5,
    coreDensity: 1.1,
    dustDensity: 1.3,
    verticalThickness: 1.5,
    starFormationDensity: 1.45,
    spiralTightness: 3.6,
  },
};

export const GALAXY_12_CONFIG: GalaxyConfig = {
  id: 'galaxy12',
  name: 'Viridis',
  subtitle: 'Lime / Teal 3-Arm Gaseous Spiral',
  description: 'Three-arm spiral with expansive gaseous clouds, asymmetric outer halo, and dense lime stellar nurseries.',
  type: 'emerald-multi-arm',
  groupId: 'groupC',
  position: [-30, 85, -340],
  rotation: [0.25, -0.4, 0.18],
  scale: 1.12,
  speed: 0.27,
  turbulence: 0.95,
  boundingRadius: 47.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.08,
    photonRingRadius: 1.58,
    accretionInnerRadius: 1.72,
    accretionOuterRadius: 8.4,
    diskTilt: [-0.25, 0.35, 0.1],
    rotationSpeed: 2.1,
    infallRate: 1.3,
    turbulence: 0.9,
    lensingStrength: 1.12,
    palette: {
      horizonRim: '#D9F99D',
      photonRing: '#F7FFE8',
      accretionInner: '#84CC16',
      accretionMid: '#14B8A6',
      accretionOuter: '#052E16',
      infallStream: '#A3E635',
    },
  },
  palette: {
    core: '#F7FFE8',
    coreHalo: '#D9F99D',
    inner: '#84CC16',
    deep: '#14B8A6',
    armsPrimary: '#14532D',
    armsSecondary: '#052E16',
    armsTertiary: '#021B0C',
    dust: '#011509',
    dustSecondary: '#052E16',
    starFormation: '#84CC16',
    starFormationWarm: '#BEF264',
    ambientStars: ['#F7FFE8', '#D9F99D', '#5EEAD4'],
  },
  morphology: {
    type: 'emerald-multi-arm',
    armCount: 3,
    asymmetry: 0.6,
    barStrength: 0.2,
    ringStrength: 0.15,
    diskFlattening: 0.48,
    coreDensity: 1.15,
    dustDensity: 1.35,
    verticalThickness: 1.6,
    starFormationDensity: 1.5,
    spiralTightness: 3.7,
  },
};

export const GALAXY_15_CONFIG: GalaxyConfig = {
  id: 'galaxy15',
  name: 'Nether',
  subtitle: 'Burgundy / Violet Broken Spiral',
  description: 'Heavily asymmetric broken spiral with giant molecular clouds, dark burgundy dust, and violent deep violet stellar regions.',
  type: 'asymmetric-broken',
  groupId: 'groupC',
  position: [-110, 28, -210],
  rotation: [-0.4, -0.2, 0.3],
  scale: 1.09,
  speed: 0.36,
  turbulence: 1.2,
  boundingRadius: 46.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.12,
    photonRingRadius: 1.62,
    accretionInnerRadius: 1.76,
    accretionOuterRadius: 8.6,
    diskTilt: [0.35, -0.3, 0.2],
    rotationSpeed: 2.5,
    infallRate: 1.55,
    turbulence: 1.2,
    lensingStrength: 1.2,
    palette: {
      horizonRim: '#FECDD3',
      photonRing: '#FFF1F2',
      accretionInner: '#E11D48',
      accretionMid: '#881337',
      accretionOuter: '#2E1065',
      infallStream: '#7E22CE',
    },
  },
  palette: {
    core: '#FFF1F2',
    coreHalo: '#FECDD3',
    inner: '#E11D48',
    deep: '#881337',
    armsPrimary: '#7E22CE',
    armsSecondary: '#4C1D95',
    armsTertiary: '#2E1065',
    dust: '#140026',
    dustSecondary: '#2E1065',
    starFormation: '#E11D48',
    starFormationWarm: '#FDA4AF',
    ambientStars: ['#FFF1F2', '#FECDD3', '#C084FC'],
  },
  morphology: {
    type: 'asymmetric-broken',
    armCount: 3,
    asymmetry: 0.85,
    barStrength: 0.4,
    ringStrength: 0.1,
    diskFlattening: 0.52,
    coreDensity: 1.25,
    dustDensity: 1.4,
    verticalThickness: 1.5,
    starFormationDensity: 1.4,
    spiralTightness: 3.4,
  },
};

// ============================================================================
// GROUP D: CELESTIAL FORGES / EXTREME PILLAR (Galaxies 06, 11, 14, 16)
// ============================================================================
export const GALAXY_06_CONFIG: GalaxyConfig = {
  id: 'galaxy06',
  name: 'Aetheris',
  subtitle: 'Celestial Forge • Extreme Centerpiece Singularity',
  description: 'The monumental visual centerpiece of the universe — an enormous 4-arm celestial spiral with a central supermassive black hole powering dual relativistic energy beams.',
  type: 'massive-energy-spiral',
  groupId: 'groupD',
  position: [165, 28, -120],
  rotation: [0.12, 0.28, -0.05],
  scale: 1.38,
  speed: 0.30,
  turbulence: 0.88,
  boundingRadius: 62.0,
  specialEffect: 'energy-jets',
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.45,
    photonRingRadius: 2.10,
    accretionInnerRadius: 2.3,
    accretionOuterRadius: 12.5,
    diskTilt: [0.15, 0.2, -0.08],
    rotationSpeed: 2.2,
    infallRate: 1.4,
    turbulence: 0.95,
    lensingStrength: 1.4,
    palette: {
      horizonRim: '#B8F5FF',
      photonRing: '#FFFFFF',
      accretionInner: '#00D9FF',
      accretionMid: '#1687FF',
      accretionOuter: '#FF6B1A',
      infallStream: '#FF9A3D',
    },
  },
  palette: {
    core: '#FFFFFF',
    coreHalo: '#FFF4E6',
    inner: '#B8F5FF',
    deep: '#00D9FF',
    armsPrimary: '#1687FF',
    armsSecondary: '#0B4DFF',
    armsTertiary: '#04142E',
    dust: '#020817',
    dustSecondary: '#0B234A',
    starFormation: '#FF6B1A',
    starFormationWarm: '#FF9A3D',
    ambientStars: ['#FFFFFF', '#B8F5FF', '#FF9A3D', '#FFC857'],
  },
  morphology: {
    type: 'massive-energy-spiral',
    armCount: 4,
    asymmetry: 0.3,
    barStrength: 0.5,
    ringStrength: 0.4,
    diskFlattening: 0.7,
    coreDensity: 1.5,
    dustDensity: 1.2,
    verticalThickness: 1.8,
    starFormationDensity: 1.4,
    spiralTightness: 3.4,
  },
};

export const GALAXY_11_CONFIG: GalaxyConfig = {
  id: 'galaxy11',
  name: 'Celestia',
  subtitle: 'Blue / Silver Thin Grand Spiral',
  description: 'Thin delicate spiral arms radiating from a dense silver-white bulge, enveloped in a vast luminous ice-blue halo.',
  type: 'thin-spiral',
  groupId: 'groupD',
  position: [260, 52, -90],
  rotation: [-0.18, 0.35, -0.15],
  scale: 1.15,
  speed: 0.28,
  turbulence: 0.8,
  boundingRadius: 48.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.15,
    photonRingRadius: 1.68,
    accretionInnerRadius: 1.85,
    accretionOuterRadius: 8.8,
    diskTilt: [-0.15, 0.25, 0.1],
    rotationSpeed: 2.0,
    infallRate: 1.25,
    turbulence: 0.82,
    lensingStrength: 1.15,
    palette: {
      horizonRim: '#DBEAFE',
      photonRing: '#FFFFFF',
      accretionInner: '#CBD5E1',
      accretionMid: '#60A5FA',
      accretionOuter: '#172554',
      infallStream: '#93C5FD',
    },
  },
  palette: {
    core: '#FFFFFF',
    coreHalo: '#DBEAFE',
    inner: '#CBD5E1',
    deep: '#60A5FA',
    armsPrimary: '#3B82F6',
    armsSecondary: '#1D4ED8',
    armsTertiary: '#172554',
    dust: '#0A1329',
    dustSecondary: '#172554',
    starFormation: '#93C5FD',
    starFormationWarm: '#E0F2FE',
    ambientStars: ['#FFFFFF', '#CBD5E1', '#60A5FA'],
  },
  morphology: {
    type: 'thin-spiral',
    armCount: 2,
    asymmetry: 0.25,
    barStrength: 0.2,
    ringStrength: 0.1,
    diskFlattening: 0.75,
    coreDensity: 1.35,
    dustDensity: 0.9,
    verticalThickness: 1.1,
    starFormationDensity: 1.2,
    spiralTightness: 3.8,
  },
};

export const GALAXY_14_CONFIG: GalaxyConfig = {
  id: 'galaxy14',
  name: 'Glacies',
  subtitle: 'Ice Blue / White Compact Spiral',
  description: 'Compact high-density spiral featuring an ultra-bright ice core, broad diffuse arms, and pure crystalline particle streams.',
  type: 'barred-spiral',
  groupId: 'groupD',
  position: [220, 15, -230],
  rotation: [0.2, -0.15, 0.35],
  scale: 1.1,
  speed: 0.32,
  turbulence: 0.85,
  boundingRadius: 46.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.1,
    photonRingRadius: 1.6,
    accretionInnerRadius: 1.75,
    accretionOuterRadius: 8.5,
    diskTilt: [0.2, -0.2, 0.3],
    rotationSpeed: 2.3,
    infallRate: 1.4,
    turbulence: 0.9,
    lensingStrength: 1.18,
    palette: {
      horizonRim: '#E0F2FE',
      photonRing: '#FFFFFF',
      accretionInner: '#7DD3FC',
      accretionMid: '#38BDF8',
      accretionOuter: '#082F49',
      infallStream: '#38BDF8',
    },
  },
  palette: {
    core: '#FFFFFF',
    coreHalo: '#E0F2FE',
    inner: '#7DD3FC',
    deep: '#38BDF8',
    armsPrimary: '#0284C7',
    armsSecondary: '#075985',
    armsTertiary: '#082F49',
    dust: '#031726',
    dustSecondary: '#082F49',
    starFormation: '#38BDF8',
    starFormationWarm: '#BAE6FD',
    ambientStars: ['#FFFFFF', '#E0F2FE', '#38BDF8'],
  },
  morphology: {
    type: 'barred-spiral',
    armCount: 2,
    asymmetry: 0.3,
    barStrength: 0.5,
    ringStrength: 0.1,
    diskFlattening: 0.65,
    coreDensity: 1.4,
    dustDensity: 0.85,
    verticalThickness: 1.25,
    starFormationDensity: 1.35,
    spiralTightness: 3.5,
  },
};

export const GALAXY_16_CONFIG: GalaxyConfig = {
  id: 'galaxy16',
  name: 'Aurelia',
  subtitle: 'Pale Gold / Cyan Multi-Arm Grand Spiral',
  description: 'Grand 4-arm spiral with pale golden nucleus, vivid cyan plasma arms, and strong starburst formations across a broad outer halo.',
  type: 'multi-arm-grand',
  groupId: 'groupD',
  position: [310, 48, -180],
  rotation: [-0.1, 0.42, 0.2],
  scale: 1.22,
  speed: 0.29,
  turbulence: 0.9,
  boundingRadius: 52.0,
  hasBlackHole: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.2,
    photonRingRadius: 1.75,
    accretionInnerRadius: 1.9,
    accretionOuterRadius: 9.5,
    diskTilt: [-0.15, 0.3, -0.1],
    rotationSpeed: 2.1,
    infallRate: 1.35,
    turbulence: 0.88,
    lensingStrength: 1.25,
    palette: {
      horizonRim: '#FFF7D6',
      photonRing: '#FFFFFF',
      accretionInner: '#FDE68A',
      accretionMid: '#67E8F9',
      accretionOuter: '#0C4A6E',
      infallStream: '#38BDF8',
    },
  },
  palette: {
    core: '#FFFFFF',
    coreHalo: '#FFF7D6',
    inner: '#FDE68A',
    deep: '#67E8F9',
    armsPrimary: '#38BDF8',
    armsSecondary: '#0284C7',
    armsTertiary: '#0C4A6E',
    dust: '#041B2B',
    dustSecondary: '#0C4A6E',
    starFormation: '#67E8F9',
    starFormationWarm: '#FEF08A',
    ambientStars: ['#FFFFFF', '#FDE68A', '#67E8F9'],
  },
  morphology: {
    type: 'multi-arm-grand',
    armCount: 4,
    asymmetry: 0.35,
    barStrength: 0.3,
    ringStrength: 0.3,
    diskFlattening: 0.6,
    coreDensity: 1.3,
    dustDensity: 1.1,
    verticalThickness: 1.5,
    starFormationDensity: 1.4,
    spiralTightness: 3.3,
  },
};

// ============================================================================
// GROUP E: IC 1579 — THE SPECIAL DEEP EXPLORATION GALAXY
// ============================================================================
export const IC1579_CONFIG: GalaxyConfig = {
  id: 'galaxy17',
  name: 'IC 1579',
  subtitle: 'Emerald Deep-Spiral • Living Ecosystem',
  description: 'An ancient emerald spiral galaxy harboring a supermassive black hole, a Dyson swarm megastructure, a tesseract-projection world, and a flagship ringed oceanic planet. The only galaxy in the cosmos where deep exploration reaches from galactic core to planetary surface and back to the night sky.',
  type: 'ic1579-emerald-spiral',
  groupId: 'groupA',
  position: [-25, 8, -12],
  rotation: [0.12, -0.08, 0.05],
  scale: 1.15,
  speed: 0.22,
  turbulence: 0.75,
  boundingRadius: 52.0,
  hasBlackHole: true,
  specialEffect: null,
  isSpecialGalaxy: true,
  blackHoleConfig: {
    eventHorizonRadius: 1.35,
    photonRingRadius: 1.95,
    accretionInnerRadius: 2.1,
    accretionOuterRadius: 10.5,
    diskTilt: [-0.15, 0.25, 0.12],
    rotationSpeed: 1.8,
    infallRate: 1.25,
    turbulence: 0.7,
    lensingStrength: 1.25,
    palette: {
      horizonRim: '#8FFFC1',
      photonRing: '#D8FFE8',
      accretionInner: '#28C7A5',
      accretionMid: '#0FA66B',
      accretionOuter: '#04281C',
      infallStream: '#A7FF5A',
    },
  },
  palette: {
    core: '#F5FFF8',
    coreHalo: '#D8FFE8',
    inner: '#8FFFC1',
    deep: '#14B8A6',
    armsPrimary: '#0FA66B',
    armsSecondary: '#075C3D',
    armsTertiary: '#04281C',
    dust: '#011509',
    dustSecondary: '#052E16',
    starFormation: '#84CC16',
    starFormationWarm: '#BEF264',
    ambientStars: ['#D8FFE8', '#8FFFC1', '#5EEAD4', '#14B8A6', '#0FA66B'],
  },
  morphology: {
    type: 'ic1579-emerald-spiral',
    armCount: 3,
    asymmetry: 0.35,
    barStrength: 0.25,
    ringStrength: 0.2,
    diskFlattening: 0.5,
    coreDensity: 1.2,
    dustDensity: 1.4,
    verticalThickness: 1.5,
    starFormationDensity: 1.3,
    spiralTightness: 3.5,
    darkLaneStrength: 0.8,
    voidStrength: 0.4,
  },
};

export const COSMIC_GROUPS: GalaxyGroupInfo[] = [
  {
    id: 'groupA',
    name: 'Local Cluster',
    designation: 'GROUP ALPHA // PRIME SECTOR',
    center: [-70, -15, -15],
    description: 'The ancient primordial galaxy group harboring the baseline spiral Aether Prime, the deep emerald ecosystem of Verdant, and the living IC 1579 ecosystem.',
    galaxyIds: ['galaxy01', 'galaxy03', 'galaxy07', 'galaxy10', 'galaxy17'],
  },
  {
    id: 'groupB',
    name: 'Southern Stream',
    designation: 'GROUP BETA // SOUTHERN STREAM',
    center: [160, -20, 180],
    description: 'A warm, dynamically energetic stream of ringed and flocculent spirals radiating intense crimson, gold, and turquoise emission.',
    galaxyIds: ['galaxy02', 'galaxy05', 'galaxy08', 'galaxy13'],
  },
  {
    id: 'groupC',
    name: 'Abyssal Ridge',
    designation: 'GROUP GAMMA // ABYSSAL RIDGE',
    center: [-80, 50, -260],
    description: 'High-contrast sector bounded by deep cosmic voids, featuring heavy golden dust lanes, broken asymmetric arms, and lime gaseous structures.',
    galaxyIds: ['galaxy04', 'galaxy09', 'galaxy12', 'galaxy15'],
  },
  {
    id: 'groupD',
    name: 'Celestial Forges',
    designation: 'GROUP DELTA // CELESTIAL PILLARS',
    center: [240, 35, -155],
    description: 'The monumental core cluster of the cosmic web, dominated by the supermassive centerpiece Aetheris with its dual relativistic energy jets.',
    galaxyIds: ['galaxy06', 'galaxy11', 'galaxy14', 'galaxy16'],
  },
];

// ============================================================================
// FULL UNIVERSE REGISTRY — ALL 17 GALAXIES (16 + IC 1579)
// ============================================================================
export const UNIVERSE_GALAXIES: GalaxyConfig[] = [
  GALAXY_01_CONFIG,
  GALAXY_02_CONFIG,
  GALAXY_03_CONFIG,
  GALAXY_04_CONFIG,
  GALAXY_05_CONFIG,
  GALAXY_06_CONFIG,
  GALAXY_07_CONFIG,
  GALAXY_08_CONFIG,
  GALAXY_09_CONFIG,
  GALAXY_10_CONFIG,
  GALAXY_11_CONFIG,
  GALAXY_12_CONFIG,
  GALAXY_13_CONFIG,
  GALAXY_14_CONFIG,
  GALAXY_15_CONFIG,
  GALAXY_16_CONFIG,
  IC1579_CONFIG,
];

export function getGalaxyConfigById(id: string): GalaxyConfig {
  const found = UNIVERSE_GALAXIES.find((g) => g.id === id);
  return found || GALAXY_01_CONFIG;
}

export function getGroupForGalaxy(galaxyId: string): GalaxyGroupInfo {
  const foundGroup = COSMIC_GROUPS.find((g) => g.galaxyIds.includes(galaxyId));
  return foundGroup || COSMIC_GROUPS[0];
}
