import type { StarSystemConfig } from '../../types/starSystem';

// ============================================================================
// IC 1579 — EMERALD DEEP-SPIRAL STAR SYSTEM CATALOG
// The special galaxy's handcrafted population: 10 discoverable systems,
// including the Dyson swarm, the tesseract-projection world, the flagship
// ringed oceanic planet, and systems riding the galactic core's shadow.
//
// Visual identity: dark emerald, forest green, cyan-green, deep teal,
// blue-green, subtle violet, black. Avoid generic purple/pink palettes.
// ============================================================================

export const IC1579_STAR_SYSTEMS: StarSystemConfig[] = [
  // ==========================================================================
  // SYSTEM 01 — CAELUM AURELIA (FLAGSHIP SYSTEM)
  // Home of Aurelia, the flagship ringed oceanic world. Deepest experience.
  // Positioned in a star-dense outer arm, ~28 units from the galactic core,
  // so the supermassive black hole is visible as a glowing emerald core
  // in the planet's night sky.
  // ==========================================================================
  {
    id: 'ic1579-flagship',
    name: 'Caelum Aurelia',
    designation: 'IC 1579 // FLAGSHIP SYSTEM 01',
    description:
      'A warm pale-gold F-type star cradling the ringed oceanic world Aurelia — an earth-like yet alien paradise wrapped in emerald seas, silver-teal rings, and a swarming orbital ecosystem of stations, satellites, and research arrays.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-24.5, 0.8, 15.2],
    systemRadius: 9.0,
    discoveryTag: 'flagship',
    discoveryTitle: 'AURELIA // THE RINGED OCEANIC WORLD',
    asteroidBelt: {
      id: 'aurelia-belt',
      name: 'Aurelian Debris Veil',
      innerRadius: 5.6,
      outerRadius: 6.1,
      count: 1100,
      height: 0.3,
      baseColor: '#1E4A38',
      accentColor: '#52E5A0',
      orbitSpeed: 0.62,
      inclination: 0.05,
    },
    star: {
      id: 'star-aurelia',
      name: 'Caelum Aurelia Prime',
      spectralType: 'F5-V • Aurelian Sun',
      apparentRadius: 0.82,
      coreColor: '#FFFDF2',
      coronaColor: '#DFFFE8',
      glowColor: '#6AE8AC',
      flareColor: '#BEF264',
      pulseSpeed: 0.95,
      coronaIntensity: 1.6,
      plasmaParticlesCount: 260,
    },
    planets: [
      {
        id: 'aurelia-p1',
        name: 'Meron',
        type: 'rocky',
        subtitle: 'Sun-Scorched Basalt World',
        description: 'A dark emerald-basalt world scoured by the Aurelian wind, its crater floors filled with green-tinged dust.',
        radius: 0.042,
        orbitRadius: 1.35,
        orbitSpeed: 1.42,
        orbitEccentricity: 0.06,
        orbitInclination: 0.04,
        orbitPhase: 0.6,
        rotationSpeed: 0.4,
        axialTilt: 0.05,
        primaryColor: '#1E3A2C',
        secondaryColor: '#0D1F17',
        accentColor: '#3F6B52',
        hasAtmosphere: false,
      },
      {
        id: 'aurelia-p2',
        name: 'Aurelia',
        type: 'earth-like',
        subtitle: 'Ringed Oceanic Flagship World',
        description:
          'A habitable earth-like world with deep teal oceans, emerald continents, vast cloud decks, and a wide ring system of pale jade ice. Orbited by research stations, comm arrays, and three moons. The deepest exploration experience in IC 1579.',
        radius: 0.115,
        orbitRadius: 2.85,
        orbitSpeed: 0.62,
        orbitEccentricity: 0.015,
        orbitInclination: 0.02,
        orbitPhase: 1.7,
        rotationSpeed: 0.24,
        axialTilt: 0.32,
        cloudRotationSpeed: 0.31,
        primaryColor: '#0A4A5A',
        secondaryColor: '#1E6B4E',
        accentColor: '#9BE8C8',
        atmosphereColor: '#5EEAD4',
        hasAtmosphere: true,
        atmosphereThickness: 0.026,
        hasClouds: true,
        rings: {
          innerRadius: 0.175,
          outerRadius: 0.42,
          color1: '#D8FFE8',
          color2: '#2E8B6F',
          opacity: 0.9,
        },
        moons: [
          {
            id: 'aurelia-m1',
            name: 'Verdanis',
            subtitle: 'Jade-Cratered Moon',
            description: 'A large cratered satellite whose maria are veined with deep green minerals.',
            radius: 0.021,
            orbitRadius: 0.55,
            orbitSpeed: 1.5,
            orbitEccentricity: 0.02,
            orbitInclination: 0.03,
            orbitPhase: 0.9,
            rotationSpeed: 0.3,
            primaryColor: '#8FD8B8',
            secondaryColor: '#3A7A5C',
            craterDensity: 0.8,
          },
          {
            id: 'aurelia-m2',
            name: 'Luneil',
            subtitle: 'Pale Ice Sentinel',
            description: 'A small bright ice moon threading the outer edge of Aurelia\'s ring system.',
            radius: 0.013,
            orbitRadius: 0.78,
            orbitSpeed: 1.1,
            orbitEccentricity: 0.04,
            orbitInclination: 0.09,
            orbitPhase: 3.4,
            rotationSpeed: 0.42,
            primaryColor: '#E8FFF2',
            secondaryColor: '#9BD8C0',
            isIcy: true,
          },
          {
            id: 'aurelia-m3',
            name: 'Umbrel',
            subtitle: 'Dark Captured Body',
            description: 'A low-albedo captured asteroid moon, nearly invisible against the night sky.',
            radius: 0.009,
            orbitRadius: 1.05,
            orbitSpeed: 0.8,
            orbitEccentricity: 0.12,
            orbitInclination: 0.22,
            orbitPhase: 5.1,
            rotationSpeed: 0.6,
            primaryColor: '#16221C',
            secondaryColor: '#0A120D',
          },
        ],
        isFlagship: true,
        surfaceExplore: true,
        hasLocalAsteroids: true,
        localAsteroidCount: 160,
      },
      {
        id: 'aurelia-p3',
        name: 'Thalor',
        type: 'ocean',
        subtitle: 'Deep Abyssal Ocean World',
        description: 'A world-covering ocean of dark teal water beneath a slow green-tinted atmosphere, lit by pale gold sunlight.',
        radius: 0.09,
        orbitRadius: 4.1,
        orbitSpeed: 0.45,
        orbitEccentricity: 0.02,
        orbitInclination: 0.04,
        orbitPhase: 4.2,
        rotationSpeed: 0.28,
        axialTilt: 0.24,
        cloudRotationSpeed: 0.33,
        primaryColor: '#06334A',
        secondaryColor: '#0E6A62',
        accentColor: '#3FE0C0',
        atmosphereColor: '#3EE0B8',
        hasAtmosphere: true,
        atmosphereThickness: 0.02,
        hasClouds: true,
        moons: [
          {
            id: 'thalor-m1',
            name: 'Neris',
            subtitle: 'Sea-Glass Moon',
            description: 'A smooth reflective moon of pale green sea glass circling the abyssal world.',
            radius: 0.016,
            orbitRadius: 0.31,
            orbitSpeed: 2.1,
            orbitEccentricity: 0.02,
            orbitInclination: 0.05,
            orbitPhase: 2.2,
            rotationSpeed: 0.36,
            primaryColor: '#A8F0D8',
            secondaryColor: '#4E9B82',
            isIcy: true,
          },
        ],
      },
      {
        id: 'aurelia-p4',
        name: 'Velok',
        type: 'gas-giant',
        subtitle: 'Emerald Banded Giant',
        description: 'A colossal gas giant with banded clouds of deep forest green, teal, and pale jade, slowly churning over centuries.',
        radius: 0.17,
        orbitRadius: 5.9,
        orbitSpeed: 0.34,
        orbitEccentricity: 0.03,
        orbitInclination: 0.03,
        orbitPhase: 1.1,
        rotationSpeed: 0.5,
        axialTilt: 0.18,
        primaryColor: '#0F6B4E',
        secondaryColor: '#2FBF86',
        accentColor: '#9BEFC8',
        atmosphereColor: '#7DF2C8',
        hasAtmosphere: true,
        atmosphereThickness: 0.042,
        moons: [
          {
            id: 'velok-m1',
            name: 'Karess',
            subtitle: 'Shattered Ice Ring Moon',
            description: 'A battered moon whose surface is scattered with the debris of an ancient shattered satellite.',
            radius: 0.018,
            orbitRadius: 0.48,
            orbitSpeed: 1.9,
            orbitEccentricity: 0.05,
            orbitInclination: 0.07,
            orbitPhase: 0.4,
            rotationSpeed: 0.45,
            primaryColor: '#B8E8D8',
            secondaryColor: '#5A8A78',
            isIcy: true,
          },
          {
            id: 'velok-m2',
            name: 'Osil',
            subtitle: 'Smoldering Ember Moon',
            description: 'A volcanic moon whose dark crust glows faintly green from mineral fires.',
            radius: 0.014,
            orbitRadius: 0.68,
            orbitSpeed: 1.4,
            orbitEccentricity: 0.03,
            orbitInclination: 0.1,
            orbitPhase: 2.9,
            rotationSpeed: 0.38,
            primaryColor: '#2A1A0A',
            secondaryColor: '#7A4E12',
            isVolcanic: true,
          },
        ],
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 02 — VARDION (DYSON SWARM)
  // A star wrapped in a slowly turning shell of orbital energy collectors.
  // Discovered naturally: at a distance it reads as an "unusual star";
  // closer, the swarm resolves into thousands of collectors.
  // ==========================================================================
  {
    id: 'ic1579-dyson',
    name: 'Vardion',
    designation: 'IC 1579 // ANOMALY 02',
    description:
      'A swollen golden star threaded through a slowly rotating swarm of orbital energy collectors — a megastructure of impossible scale drifting in the deep arms of IC 1579.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [17.5, -1.2, -19.0],
    systemRadius: 10.0,
    discoveryTag: 'dyson',
    discoveryTitle: 'VARDION // ORBITAL COLLECTOR SWARM',
    star: {
      id: 'star-vardion',
      name: 'Vardion Prime',
      spectralType: 'G2-V • Collector Star',
      apparentRadius: 0.9,
      coreColor: '#FFF9E8',
      coronaColor: '#FFE9A8',
      glowColor: '#F5B93E',
      flareColor: '#FFE082',
      pulseSpeed: 0.7,
      coronaIntensity: 1.9,
      plasmaParticlesCount: 320,
    },
    dysonSwarm: {
      id: 'vardion-swarm',
      name: 'Vardion Collector Swarm',
      innerRadius: 1.55,
      outerRadius: 2.75,
      collectorCount: 4200,
      panelColor: '#1A3528',
      glowColor: '#52E5A0',
      orbitTilt: [-0.08, 0.14, -0.05],
      rotationSpeed: 0.22,
      thermalGlow: 0.95,
    },
    planets: [
      {
        id: 'vardion-p1',
        name: 'Skindrel',
        type: 'hot-lava',
        subtitle: 'Shadowed Magma World',
        description: 'A world caught between the collector swarm\'s eclipse and the star\'s heat, its crust in permanent violent resurfacing.',
        radius: 0.05,
        orbitRadius: 3.4,
        orbitSpeed: 1.15,
        orbitEccentricity: 0.05,
        orbitInclination: 0.06,
        orbitPhase: 0.3,
        rotationSpeed: 0.32,
        axialTilt: 0.04,
        primaryColor: '#1A0E04',
        secondaryColor: '#E85D04',
        accentColor: '#FFB84D',
        atmosphereColor: '#FF7B24',
        hasAtmosphere: true,
        atmosphereThickness: 0.012,
      },
      {
        id: 'vardion-p2',
        name: 'Morkad',
        type: 'ice',
        subtitle: 'Dim Far Cryo World',
        description: 'A remote ice world lying in the swarm\'s long shadow, its nitrogen glaciers tinted faint green.',
        radius: 0.072,
        orbitRadius: 6.2,
        orbitSpeed: 0.52,
        orbitEccentricity: 0.04,
        orbitInclination: 0.07,
        orbitPhase: 4.7,
        rotationSpeed: 0.3,
        axialTilt: 0.14,
        primaryColor: '#9EDCC8',
        secondaryColor: '#E8FFF4',
        accentColor: '#2E7A62',
        atmosphereColor: '#BFF5E0',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
        moons: [
          {
            id: 'morkad-m1',
            name: 'Korren',
            subtitle: 'Frozen Husk',
            description: 'A long-dead rocky moon of the dim cryo world.',
            radius: 0.014,
            orbitRadius: 0.24,
            orbitSpeed: 2.4,
            orbitEccentricity: 0.06,
            orbitInclination: 0.12,
            orbitPhase: 1.5,
            rotationSpeed: 0.4,
            primaryColor: '#5A6A62',
            secondaryColor: '#2E3A34',
          },
        ],
      },
      {
        id: 'vardion-p3',
        name: 'Veilhaven',
        type: 'earth-like',
        subtitle: 'Swarm-Lit Habitable World',
        description:
          'A habitable world orbiting beyond the collector swarm, its golden-green continents warmed by the light of Vardion Prime leaking between the rotating collectors. At night, the swarm hangs overhead as a slow river of emerald fire — the only planet from which the megastructure is best observed.',
        radius: 0.098,
        orbitRadius: 4.6,
        orbitSpeed: 0.68,
        orbitEccentricity: 0.02,
        orbitInclination: 0.03,
        orbitPhase: 2.8,
        rotationSpeed: 0.26,
        axialTilt: 0.3,
        cloudRotationSpeed: 0.32,
        primaryColor: '#0A4A38',
        secondaryColor: '#2E7A4E',
        accentColor: '#E8C87A',
        atmosphereColor: '#7AE8B8',
        hasAtmosphere: true,
        atmosphereThickness: 0.024,
        hasClouds: true,
        surfaceExplore: true,
        moons: [
          {
            id: 'veilhaven-m1',
            name: 'Sunder',
            subtitle: 'Fractured Watchman Moon',
            description: 'A large broken moon whose far side is continuously lit by the collector swarm.',
            radius: 0.02,
            orbitRadius: 0.45,
            orbitSpeed: 1.8,
            orbitEccentricity: 0.04,
            orbitInclination: 0.06,
            orbitPhase: 1.1,
            rotationSpeed: 0.28,
            primaryColor: '#C8B898',
            secondaryColor: '#6E5E42',
          },
        ],
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 03 — XENORA (TESSERACT-PROJECTION WORLD)
  // A pale white star harboring a world whose surface betrays a structure
  // projected from higher-dimensional mathematics: a tesseract.
  // ==========================================================================
  {
    id: 'ic1579-tesseract',
    name: 'Xenora',
    designation: 'IC 1579 // ANOMALY 03',
    description:
      'A quiet white subdwarf star encircled by a world of impossible geometry — a structure rendered from a four-dimensional hypercube, rotating in planes no human eye should see.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [8.6, 2.1, 27.0],
    systemRadius: 7.0,
    discoveryTag: 'tesseract',
    discoveryTitle: 'XENORA // TESSERACT-PROJECTION WORLD',
    star: {
      id: 'star-xenora',
      name: 'Xenora Prime',
      spectralType: 'A2-V • Pale Subdwarf',
      apparentRadius: 0.55,
      coreColor: '#F4FFFF',
      coronaColor: '#D4FFF5',
      glowColor: '#6EE7D8',
      flareColor: '#9BE8E0',
      pulseSpeed: 1.25,
      coronaIntensity: 1.8,
      plasmaParticlesCount: 240,
    },
    planets: [
      {
        id: 'xenora-p1',
        name: 'Tessera',
        type: 'earth-like',
        subtitle: 'Tesseract-Projection World',
        description:
          'At a distance, an unremarkable pale emerald world. Close up, its mountain chains resolve into the edges of a rotating four-dimensional hypercube — faces folding through the sky, impossible corners arriving from nowhere, geometry obeying mathematics beyond three dimensions.',
        radius: 0.1,
        orbitRadius: 2.1,
        orbitSpeed: 0.85,
        orbitEccentricity: 0.01,
        orbitInclination: 0.02,
        orbitPhase: 2.4,
        rotationSpeed: 0.18,
        axialTilt: 0.4,
        primaryColor: '#0E4A3A',
        secondaryColor: '#2E8B6F',
        accentColor: '#9BE8C8',
        atmosphereColor: '#5EEAD4',
        hasAtmosphere: true,
        atmosphereThickness: 0.024,
        hasClouds: true,
        surfaceExplore: true,
        tesseract: {
          projectionScale: 0.5,
          color: '#8FFFC1',
          secondaryColor: '#8B5CF6',
          rotationSpeed: 0.55,
          anomalyStrength: 0.6,
        },
        moons: [
          {
            id: 'tessera-m1',
            name: 'Facet',
            subtitle: 'Cuboid Moonlet',
            description: 'A small moon that — from certain angles — appears to have square faces.',
            radius: 0.017,
            orbitRadius: 0.35,
            orbitSpeed: 1.9,
            orbitEccentricity: 0.02,
            orbitInclination: 0.04,
            orbitPhase: 1.3,
            rotationSpeed: 0.5,
            primaryColor: '#BFE8DC',
            secondaryColor: '#5A8A7C',
          },
        ],
      },
      {
        id: 'xenora-p2',
        name: 'Veskel',
        type: 'rocky',
        subtitle: 'Shattered Grey World',
        description: 'A cracked, airless world whose long straight canyons seem to align to unseen axes.',
        radius: 0.058,
        orbitRadius: 3.3,
        orbitSpeed: 0.72,
        orbitEccentricity: 0.07,
        orbitInclination: 0.06,
        orbitPhase: 5.2,
        rotationSpeed: 0.26,
        axialTilt: 0.1,
        primaryColor: '#4A5A52',
        secondaryColor: '#222C28',
        accentColor: '#7E9A8C',
        hasAtmosphere: false,
      },
      {
        id: 'xenora-p3',
        name: 'Oren',
        type: 'dense-atmosphere',
        subtitle: 'Green-Veil Cloud World',
        description: 'A high-pressure world smothered in pale green aerosol veils with slow banded storms.',
        radius: 0.095,
        orbitRadius: 4.9,
        orbitSpeed: 0.5,
        orbitEccentricity: 0.03,
        orbitInclination: 0.05,
        orbitPhase: 3.6,
        rotationSpeed: 0.4,
        axialTilt: 0.3,
        primaryColor: '#0E4E3C',
        secondaryColor: '#52C8A4',
        accentColor: '#E8F2B0',
        atmosphereColor: '#B8E8C8',
        hasAtmosphere: true,
        atmosphereThickness: 0.03,
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 04 — VERDANT HEARTH (GALACTIC CORE VICINITY)
  // An ancient K-type star orbiting perilously close to the supermassive
  // black hole's glow, in the deep emerald core of IC 1579.
  // ==========================================================================
  {
    id: 'ic1579-verdant-core',
    name: 'Verdant Hearth',
    designation: 'IC 1579 // CORE VICINITY 04',
    description:
      'An ancient amber-gold star swinging close to the supermassive black hole of IC 1579, its planets lit by both star and accretion glow.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [5.2, 0.6, -6.8],
    systemRadius: 6.5,
    discoveryTag: 'core-vicinity',
    discoveryTitle: 'VERDANT HEARTH // BLACK HOLE VICINITY',
    star: {
      id: 'star-verdant',
      name: 'Verdant Hearth Core',
      spectralType: 'K1-V • Amber Dwarf',
      apparentRadius: 0.7,
      coreColor: '#FFF4DC',
      coronaColor: '#FFD9A0',
      glowColor: '#F5A63E',
      flareColor: '#FFE4B0',
      pulseSpeed: 1.05,
      coronaIntensity: 1.5,
      plasmaParticlesCount: 220,
    },
    planets: [
      {
        id: 'verdant-p1',
        name: 'Ashyn',
        type: 'hot-lava',
        subtitle: 'Twin-Heat World',
        description: 'A world cooked by two heat sources: its star and the distant accretion disk of the central black hole.',
        radius: 0.055,
        orbitRadius: 1.2,
        orbitSpeed: 1.6,
        orbitEccentricity: 0.08,
        orbitInclination: 0.05,
        orbitPhase: 0.9,
        rotationSpeed: 0.3,
        axialTilt: 0.03,
        primaryColor: '#2E0E02',
        secondaryColor: '#E85D04',
        accentColor: '#FFD060',
        atmosphereColor: '#FF8B3A',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
      },
      {
        id: 'verdant-p2',
        name: 'Thren',
        type: 'rocky',
        subtitle: 'Green-Black Cinder World',
        description: 'A dark cinder world whose cratered plains glint faintly in the black hole\'s emerald light.',
        radius: 0.062,
        orbitRadius: 2.0,
        orbitSpeed: 1.05,
        orbitEccentricity: 0.05,
        orbitInclination: 0.03,
        orbitPhase: 3.8,
        rotationSpeed: 0.34,
        axialTilt: 0.07,
        primaryColor: '#12241C',
        secondaryColor: '#0A1410',
        accentColor: '#2E5A44',
        hasAtmosphere: false,
        surfaceExplore: true,
      },
      {
        id: 'verdant-p3',
        name: 'Sablehollow',
        type: 'ice',
        subtitle: 'Dark Ice World',
        description: 'A dim frozen world orbiting at the system\'s edge, half-visible against the core\'s glow.',
        radius: 0.07,
        orbitRadius: 3.6,
        orbitSpeed: 0.68,
        orbitEccentricity: 0.06,
        orbitInclination: 0.08,
        orbitPhase: 2.1,
        rotationSpeed: 0.28,
        axialTilt: 0.2,
        primaryColor: '#6E8A7C',
        secondaryColor: '#D8F0E4',
        accentColor: '#2E4A3E',
        atmosphereColor: '#8ED8C0',
        hasAtmosphere: true,
        atmosphereThickness: 0.012,
        moons: [
          {
            id: 'sablehollow-m1',
            name: 'Gloom',
            subtitle: 'Shadowed Moon',
            description: 'A dim moon forever caught in the dark side of its parent world.',
            radius: 0.013,
            orbitRadius: 0.22,
            orbitSpeed: 2.5,
            orbitEccentricity: 0.04,
            orbitInclination: 0.1,
            orbitPhase: 4.4,
            rotationSpeed: 0.36,
            primaryColor: '#3A4A42',
            secondaryColor: '#1C2420',
          },
        ],
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 05 — JADE STREAM
  // A cool teal star with a ringed ice giant and a crescent ocean world.
  // ==========================================================================
  {
    id: 'ic1579-jade-stream',
    name: 'Jade Stream',
    designation: 'IC 1579 // SYSTEM 05',
    description:
      'A cool teal star pouring a slow river of green light through its system of ice and water worlds.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-12.0, -1.4, -22.5],
    systemRadius: 8.5,
    star: {
      id: 'star-jade',
      name: 'Jade Stream Core',
      spectralType: 'F8-V • Teal Dwarf',
      apparentRadius: 0.68,
      coreColor: '#F0FFF8',
      coronaColor: '#B8FFD8',
      glowColor: '#3EE0B8',
      flareColor: '#8FFFC1',
      pulseSpeed: 1.15,
      coronaIntensity: 1.6,
      plasmaParticlesCount: 240,
    },
    planets: [
      {
        id: 'jade-p1',
        name: 'Creska',
        type: 'ocean',
        subtitle: 'Crescent Ocean World',
        description: 'A world of pale teal oceans ringed by a thin atmosphere of green mist.',
        radius: 0.085,
        orbitRadius: 1.9,
        orbitSpeed: 1.05,
        orbitEccentricity: 0.02,
        orbitInclination: 0.03,
        orbitPhase: 1.2,
        rotationSpeed: 0.3,
        axialTilt: 0.22,
        cloudRotationSpeed: 0.35,
        primaryColor: '#0A4E46',
        secondaryColor: '#14A87E',
        accentColor: '#8FF0C8',
        atmosphereColor: '#4EE0B0',
        hasAtmosphere: true,
        atmosphereThickness: 0.02,
        hasClouds: true,
        surfaceExplore: true,
        moons: [
          {
            id: 'creska-m1',
            name: 'Sliver',
            subtitle: 'Thin Crescent Moon',
            description: 'A sliver-shaped moon orbiting close to its ocean world.',
            radius: 0.011,
            orbitRadius: 0.21,
            orbitSpeed: 2.8,
            orbitEccentricity: 0.02,
            orbitInclination: 0.05,
            orbitPhase: 3.3,
            rotationSpeed: 0.5,
            primaryColor: '#C8F0E0',
            secondaryColor: '#6EA898',
          },
        ],
      },
      {
        id: 'jade-p2',
        name: 'Morne',
        type: 'ringed-giant',
        subtitle: 'Jade-Ringed Ice Giant',
        description: 'A pale blue-green ice giant crowned by a wide, layered ring system of frost and shattered ice.',
        radius: 0.14,
        orbitRadius: 3.5,
        orbitSpeed: 0.6,
        orbitEccentricity: 0.02,
        orbitInclination: 0.04,
        orbitPhase: 4.5,
        rotationSpeed: 0.45,
        axialTilt: 0.5,
        primaryColor: '#2E8B8A',
        secondaryColor: '#B8E8E4',
        accentColor: '#14403E',
        atmosphereColor: '#7ADBD0',
        hasAtmosphere: true,
        atmosphereThickness: 0.034,
        rings: {
          innerRadius: 0.2,
          outerRadius: 0.42,
          color1: '#D8FFF0',
          color2: '#6EBCA8',
          opacity: 0.88,
        },
        moons: [
          {
            id: 'morne-m1',
            name: 'Dreyd',
            subtitle: 'Frost Fracture Moon',
            description: 'A moon criss-crossed by bright frozen fractures, orbiting beyond the ring plane.',
            radius: 0.019,
            orbitRadius: 0.6,
            orbitSpeed: 1.5,
            orbitEccentricity: 0.03,
            orbitInclination: 0.08,
            orbitPhase: 1.8,
            rotationSpeed: 0.32,
            primaryColor: '#E0F8F0',
            secondaryColor: '#8AC0B0',
            isIcy: true,
          },
        ],
      },
      {
        id: 'jade-p3',
        name: 'Orn',
        type: 'dark-banded',
        subtitle: 'Green-Lit Dark World',
        description: 'An ultra-dark world whose equatorial haze glows faint emerald under the teal star.',
        radius: 0.09,
        orbitRadius: 5.2,
        orbitSpeed: 0.44,
        orbitEccentricity: 0.04,
        orbitInclination: 0.07,
        orbitPhase: 2.7,
        rotationSpeed: 0.24,
        axialTilt: 0.12,
        primaryColor: '#0A140E',
        secondaryColor: '#123A2A',
        accentColor: '#3EE0A0',
        atmosphereColor: '#3ED8A8',
        hasAtmosphere: true,
        atmosphereThickness: 0.026,
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 06 — THE SENTINEL
  // A luminous blue-white giant at the tip of an arm — a stellar beacon
  // visible from across the galaxy.
  // ==========================================================================
  {
    id: 'ic1579-sentinel',
    name: 'The Sentinel',
    designation: 'IC 1579 // SYSTEM 06',
    description:
      'A searing blue-white giant standing watch at the broken tip of IC 1579\'s outermost arm, hurling pale cyan light across the void.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [26.0, 0.4, -8.5],
    systemRadius: 9.0,
    discoveryTag: 'sentinel',
    discoveryTitle: 'THE SENTINEL // BLUE-WHITE GIANT',
    asteroidBelt: {
      id: 'sentinel-belt',
      name: 'Sentinel Scorch Belt',
      innerRadius: 4.8,
      outerRadius: 5.3,
      count: 900,
      height: 0.25,
      baseColor: '#4E6A7C',
      accentColor: '#B8E8FF',
      orbitSpeed: 0.75,
      inclination: 0.04,
    },
    star: {
      id: 'star-sentinel',
      name: 'Sentinel Core',
      spectralType: 'B1-V • Blue Giant',
      apparentRadius: 1.4,
      coreColor: '#F0FAFF',
      coronaColor: '#C8F0FF',
      glowColor: '#5EA8E8',
      flareColor: '#A8E0FF',
      pulseSpeed: 0.8,
      coronaIntensity: 2.2,
      plasmaParticlesCount: 360,
    },
    planets: [
      {
        id: 'sentinel-p1',
        name: 'Skar',
        type: 'rocky',
        subtitle: 'Bleached Ash World',
        description: 'A world stripped bare by the giant\'s radiation, its surface pale ash beneath a sky of harsh cyan.',
        radius: 0.05,
        orbitRadius: 2.2,
        orbitSpeed: 1.35,
        orbitEccentricity: 0.07,
        orbitInclination: 0.05,
        orbitPhase: 0.7,
        rotationSpeed: 0.3,
        axialTilt: 0.06,
        primaryColor: '#8E9AA2',
        secondaryColor: '#4A5258',
        accentColor: '#C8D4DC',
        hasAtmosphere: false,
      },
      {
        id: 'sentinel-p2',
        name: 'Dregan',
        type: 'dense-atmosphere',
        subtitle: 'Cyan Veil World',
        description: 'A high-pressure world wrapped in deep cyan haze, lit from above by the blazing giant.',
        radius: 0.12,
        orbitRadius: 4.4,
        orbitSpeed: 0.72,
        orbitEccentricity: 0.03,
        orbitInclination: 0.04,
        orbitPhase: 3.1,
        rotationSpeed: 0.38,
        axialTilt: 0.2,
        primaryColor: '#14445A',
        secondaryColor: '#3E96B8',
        accentColor: '#A8E8FF',
        atmosphereColor: '#6AC8E8',
        hasAtmosphere: true,
        atmosphereThickness: 0.036,
        moons: [
          {
            id: 'dregan-m1',
            name: 'Veyl',
            subtitle: 'Mist-Enshrouded Moon',
            description: 'A moon perpetually wrapped in thin cyan mist.',
            radius: 0.015,
            orbitRadius: 0.34,
            orbitSpeed: 2.2,
            orbitEccentricity: 0.03,
            orbitInclination: 0.06,
            orbitPhase: 2.5,
            rotationSpeed: 0.4,
            primaryColor: '#8EC8DC',
            secondaryColor: '#4E8EA2',
          },
        ],
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 07 — SABLE VEIL
  // An orange star deep inside a heavy dust lane; its light is dimmed and
  // reddened by the surrounding molecular cloud.
  // ==========================================================================
  {
    id: 'ic1579-sable-veil',
    name: 'Sable Veil',
    designation: 'IC 1579 // SYSTEM 07',
    description:
      'An orange dwarf half-hidden inside a dense molecular cloud, its amber light diffusing through curtains of dark green dust.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-30.0, -2.2, 6.5],
    systemRadius: 6.0,
    star: {
      id: 'star-sable',
      name: 'Sable Veil Core',
      spectralType: 'K3-V • Obscured Orange Dwarf',
      apparentRadius: 0.62,
      coreColor: '#FFF0D0',
      coronaColor: '#FFD090',
      glowColor: '#E8A040',
      flareColor: '#FFDCA8',
      pulseSpeed: 1.1,
      coronaIntensity: 1.2,
      plasmaParticlesCount: 200,
    },
    planets: [
      {
        id: 'sable-p1',
        name: 'Tarn',
        type: 'rocky',
        subtitle: 'Dust-Choked World',
        description: 'A cratered world buried under drifting dust, its surface a dark umber shadow.',
        radius: 0.052,
        orbitRadius: 1.4,
        orbitSpeed: 1.3,
        orbitEccentricity: 0.06,
        orbitInclination: 0.05,
        orbitPhase: 1.9,
        rotationSpeed: 0.3,
        axialTilt: 0.05,
        primaryColor: '#3E2E1A',
        secondaryColor: '#1C140A',
        accentColor: '#7A5A2E',
        hasAtmosphere: false,
      },
      {
        id: 'sable-p2',
        name: 'Ravnen',
        type: 'dense-atmosphere',
        subtitle: 'Amber Mist World',
        description: 'A thick-atmosphere world seen only as a glowing amber disc through the dust.',
        radius: 0.1,
        orbitRadius: 2.6,
        orbitSpeed: 0.85,
        orbitEccentricity: 0.03,
        orbitInclination: 0.04,
        orbitPhase: 4.2,
        rotationSpeed: 0.36,
        axialTilt: 0.25,
        primaryColor: '#6E3E0E',
        secondaryColor: '#E8A850',
        accentColor: '#FFD890',
        atmosphereColor: '#F0B860',
        hasAtmosphere: true,
        atmosphereThickness: 0.03,
        moons: [
          {
            id: 'ravnen-m1',
            name: 'Emla',
            subtitle: 'Ember-Colored Moon',
            description: 'A warm-toned moon peeking through the veil of dust.',
            radius: 0.013,
            orbitRadius: 0.28,
            orbitSpeed: 2.3,
            orbitEccentricity: 0.04,
            orbitInclination: 0.09,
            orbitPhase: 0.5,
            rotationSpeed: 0.42,
            primaryColor: '#B8A888',
            secondaryColor: '#6E5E42',
          },
        ],
      },
      {
        id: 'sable-p3',
        name: 'Umbra Deep',
        type: 'ice',
        subtitle: 'Twilight Ice World',
        description: 'A dim ice world lingering at the dust cloud\'s edge, its frost lit amber-orange.',
        radius: 0.066,
        orbitRadius: 4.1,
        orbitSpeed: 0.55,
        orbitEccentricity: 0.05,
        orbitInclination: 0.07,
        orbitPhase: 3.3,
        rotationSpeed: 0.28,
        axialTilt: 0.16,
        primaryColor: '#8EA8B8',
        secondaryColor: '#E0E8E8',
        accentColor: '#4E6A78',
        atmosphereColor: '#A8C8D8',
        hasAtmosphere: true,
        atmosphereThickness: 0.012,
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 08 — AZURE VERGE
  // A blue-white A-type star with a busy system of five worlds, two giants
  // and an inner scorched chain.
  // ==========================================================================
  {
    id: 'ic1579-azure-verge',
    name: 'Azure Verge',
    designation: 'IC 1579 // SYSTEM 08',
    description:
      'A luminous blue-white star on the edge of a stellar nursery, its five worlds lit by cold blue flame.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-20.0, 1.8, 30.0],
    systemRadius: 9.5,
    star: {
      id: 'star-azure',
      name: 'Azure Verge Core',
      spectralType: 'A0-V • Blue-White Star',
      apparentRadius: 0.78,
      coreColor: '#F4FCFF',
      coronaColor: '#C8E8FF',
      glowColor: '#6EA8F0',
      flareColor: '#A8D8FF',
      pulseSpeed: 1.2,
      coronaIntensity: 1.9,
      plasmaParticlesCount: 280,
    },
    planets: [
      {
        id: 'azure-p1',
        name: 'Kes',
        type: 'rocky',
        subtitle: 'Blue-Baked Rock',
        description: 'A bare rock world scoured by the star\'s ultraviolet wind.',
        radius: 0.044,
        orbitRadius: 1.2,
        orbitSpeed: 1.5,
        orbitEccentricity: 0.05,
        orbitInclination: 0.03,
        orbitPhase: 2.0,
        rotationSpeed: 0.35,
        axialTilt: 0.04,
        primaryColor: '#5E6E8A',
        secondaryColor: '#2E3A4E',
        accentColor: '#9AB0C8',
        hasAtmosphere: false,
      },
      {
        id: 'azure-p2',
        name: 'Vesh',
        type: 'hot-lava',
        subtitle: 'Blue-Ember Lava World',
        description: 'A lava world whose molten seas glow cyan-white under the fierce blue star.',
        radius: 0.06,
        orbitRadius: 1.9,
        orbitSpeed: 1.1,
        orbitEccentricity: 0.04,
        orbitInclination: 0.05,
        orbitPhase: 4.6,
        rotationSpeed: 0.3,
        axialTilt: 0.03,
        primaryColor: '#1A2430',
        secondaryColor: '#4EC8F0',
        accentColor: '#B8F0FF',
        atmosphereColor: '#6AD8F8',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
      },
      {
        id: 'azure-p3',
        name: 'Thalume',
        type: 'ocean',
        subtitle: 'Cold Cyan Ocean World',
        description: 'A deep ocean world of cold cyan water beneath thin blue ice-haze.',
        radius: 0.095,
        orbitRadius: 3.2,
        orbitSpeed: 0.72,
        orbitEccentricity: 0.02,
        orbitInclination: 0.03,
        orbitPhase: 1.4,
        rotationSpeed: 0.3,
        axialTilt: 0.26,
        cloudRotationSpeed: 0.34,
        primaryColor: '#0A3E6E',
        secondaryColor: '#2E86B8',
        accentColor: '#A8E0F8',
        atmosphereColor: '#5AB8E8',
        hasAtmosphere: true,
        atmosphereThickness: 0.02,
        hasClouds: true,
        moons: [
          {
            id: 'thalume-m1',
            name: 'Wren',
            subtitle: 'Pale Blue Moon',
            description: 'A smooth ice moon circling the cold ocean world.',
            radius: 0.016,
            orbitRadius: 0.3,
            orbitSpeed: 2.2,
            orbitEccentricity: 0.02,
            orbitInclination: 0.04,
            orbitPhase: 2.8,
            rotationSpeed: 0.38,
            primaryColor: '#C8E8F8',
            secondaryColor: '#7AA8C0',
            isIcy: true,
          },
        ],
      },
      {
        id: 'azure-p4',
        name: 'Zeral',
        type: 'gas-giant',
        subtitle: 'Pale Blue Banded Giant',
        description: 'A serene banded giant of pale blues and white storm streaks.',
        radius: 0.16,
        orbitRadius: 4.8,
        orbitSpeed: 0.5,
        orbitEccentricity: 0.03,
        orbitInclination: 0.05,
        orbitPhase: 3.7,
        rotationSpeed: 0.52,
        axialTilt: 0.28,
        primaryColor: '#3E6E9E',
        secondaryColor: '#B8D8F0',
        accentColor: '#1E3E5E',
        atmosphereColor: '#7AC0E8',
        hasAtmosphere: true,
        atmosphereThickness: 0.038,
        moons: [
          {
            id: 'zeral-m1',
            name: 'Syr',
            subtitle: 'Storm-Washed Moon',
            description: 'A small moon whose pale surface is dusted by the giant\'s ring particles.',
            radius: 0.014,
            orbitRadius: 0.44,
            orbitSpeed: 2.0,
            orbitEccentricity: 0.03,
            orbitInclination: 0.06,
            orbitPhase: 1.1,
            rotationSpeed: 0.44,
            primaryColor: '#B8D0E0',
            secondaryColor: '#6E8AA0',
          },
        ],
      },
      {
        id: 'azure-p5',
        name: 'Nym',
        type: 'ice',
        subtitle: 'Distant Blue Ice',
        description: 'A far ice world with nitrogen glaciers glowing faint blue in the starlight.',
        radius: 0.07,
        orbitRadius: 6.6,
        orbitSpeed: 0.38,
        orbitEccentricity: 0.06,
        orbitInclination: 0.08,
        orbitPhase: 5.4,
        rotationSpeed: 0.32,
        axialTilt: 0.18,
        primaryColor: '#8EB8D8',
        secondaryColor: '#E8F4FC',
        accentColor: '#4E7EA0',
        atmosphereColor: '#B0D8F0',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 09 — EMERALD HALO
  // A dim red dwarf lost in the outer halo of IC 1579, above the disk plane.
  // ==========================================================================
  {
    id: 'ic1579-emerald-halo',
    name: 'Emerald Halo',
    designation: 'IC 1579 // SYSTEM 09',
    description:
      'A dim red dwarf floating high above the galactic plane in IC 1579\'s sparse outer halo — a lonely ember in the dark.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-8.5, 6.5, -33.0],
    systemRadius: 5.0,
    discoveryTag: 'halo-remnant',
    discoveryTitle: 'EMERALD HALO // HALO REMNANT',
    star: {
      id: 'star-emerald-halo',
      name: 'Halo Ember',
      spectralType: 'M4-V • Dim Red Dwarf',
      apparentRadius: 0.42,
      coreColor: '#FFE8D0',
      coronaColor: '#FF9E5E',
      glowColor: '#D85A2E',
      flareColor: '#FFC8A0',
      pulseSpeed: 1.35,
      coronaIntensity: 1.1,
      plasmaParticlesCount: 180,
    },
    planets: [
      {
        id: 'halo-p1',
        name: 'Cindr',
        type: 'rocky',
        subtitle: 'Ember Rock',
        description: 'A small rock world hugging its dim sun, its dark surface faintly warm.',
        radius: 0.04,
        orbitRadius: 0.9,
        orbitSpeed: 1.8,
        orbitEccentricity: 0.07,
        orbitInclination: 0.04,
        orbitPhase: 3.0,
        rotationSpeed: 0.4,
        axialTilt: 0.08,
        primaryColor: '#3E2412',
        secondaryColor: '#1E1008',
        accentColor: '#8A5A2E',
        hasAtmosphere: false,
      },
      {
        id: 'halo-p2',
        name: 'Vesperel',
        type: 'ice',
        subtitle: 'Halo Twilight World',
        description: 'A frozen world alone in the halo, its ice catching the faint red light of its sun and the distant emerald glow of IC 1579 below.',
        radius: 0.068,
        orbitRadius: 2.3,
        orbitSpeed: 0.9,
        orbitEccentricity: 0.04,
        orbitInclination: 0.06,
        orbitPhase: 1.6,
        rotationSpeed: 0.26,
        axialTilt: 0.2,
        primaryColor: '#9EB0B8',
        secondaryColor: '#E0E8E8',
        accentColor: '#4E6068',
        atmosphereColor: '#A8C0C8',
        hasAtmosphere: true,
        atmosphereThickness: 0.01,
        moons: [
          {
            id: 'vesperel-m1',
            name: 'Nyxa',
            subtitle: 'Dark Companion',
            description: 'A small dark moon circling the halo world.',
            radius: 0.011,
            orbitRadius: 0.2,
            orbitSpeed: 2.6,
            orbitEccentricity: 0.05,
            orbitInclination: 0.12,
            orbitPhase: 5.6,
            rotationSpeed: 0.48,
            primaryColor: '#2E3238',
            secondaryColor: '#141618',
          },
        ],
      },
    ],
  },

  // ==========================================================================
  // SYSTEM 10 — UMBRA WEAVE
  // A quiet red dwarf in a torn nebula at the galaxy's rim — a nursery of
  // dark dust and young planets.
  // ==========================================================================
  {
    id: 'ic1579-nebula-rim',
    name: 'Umbra Weave',
    designation: 'IC 1579 // SYSTEM 10',
    description:
      'A young red dwarf caught in a torn emerald nebula at IC 1579\'s rim, its planets still settling among the dust.',
    galaxyId: 'galaxy17',
    positionInGalaxy: [-34.0, 0.5, -14.0],
    systemRadius: 6.0,
    star: {
      id: 'star-umbra',
      name: 'Umbra Weave Core',
      spectralType: 'M2-V • Nebular Red Dwarf',
      apparentRadius: 0.48,
      coreColor: '#FFE0C0',
      coronaColor: '#FFA05A',
      glowColor: '#E05A28',
      flareColor: '#FFB878',
      pulseSpeed: 1.2,
      coronaIntensity: 1.3,
      plasmaParticlesCount: 200,
    },
    planets: [
      {
        id: 'umbra-p1',
        name: 'Rust',
        type: 'rocky',
        subtitle: 'Rust-Red World',
        description: 'A young rock world dusted with oxidized minerals and nebular ash.',
        radius: 0.055,
        orbitRadius: 1.3,
        orbitSpeed: 1.4,
        orbitEccentricity: 0.08,
        orbitInclination: 0.05,
        orbitPhase: 1.1,
        rotationSpeed: 0.3,
        axialTilt: 0.06,
        primaryColor: '#6E3A1A',
        secondaryColor: '#3A1A0A',
        accentColor: '#B8804E',
        hasAtmosphere: false,
        hasLocalAsteroids: true,
        localAsteroidCount: 90,
      },
      {
        id: 'umbra-p2',
        name: 'Vassa',
        type: 'ocean',
        subtitle: 'Young Dark Ocean',
        description: 'A newborn ocean world whose dark green seas are still clearing of dust.',
        radius: 0.088,
        orbitRadius: 2.2,
        orbitSpeed: 0.92,
        orbitEccentricity: 0.03,
        orbitInclination: 0.04,
        orbitPhase: 4.0,
        rotationSpeed: 0.32,
        axialTilt: 0.28,
        cloudRotationSpeed: 0.36,
        primaryColor: '#0A3E32',
        secondaryColor: '#1E7A5E',
        accentColor: '#7AE0B8',
        atmosphereColor: '#5AD8B0',
        hasAtmosphere: true,
        atmosphereThickness: 0.022,
        hasClouds: true,
        moons: [
          {
            id: 'vassa-m1',
            name: 'Silt',
            subtitle: 'Dust-Covered Moon',
            description: 'A moon still blanketed by the surrounding nebula\'s dust.',
            radius: 0.014,
            orbitRadius: 0.27,
            orbitSpeed: 2.4,
            orbitEccentricity: 0.04,
            orbitInclination: 0.07,
            orbitPhase: 2.0,
            rotationSpeed: 0.4,
            primaryColor: '#8A6E4E',
            secondaryColor: '#4A3820',
          },
        ],
      },
      {
        id: 'umbra-p3',
        name: 'Keld',
        type: 'dense-atmosphere',
        subtitle: 'Emerald Smog World',
        description: 'A young world smothered in thick emerald photochemical haze.',
        radius: 0.1,
        orbitRadius: 3.6,
        orbitSpeed: 0.62,
        orbitEccentricity: 0.05,
        orbitInclination: 0.06,
        orbitPhase: 3.9,
        rotationSpeed: 0.34,
        axialTilt: 0.24,
        primaryColor: '#0E4A2E',
        secondaryColor: '#52C868',
        accentColor: '#B8E888',
        atmosphereColor: '#8AE85A',
        hasAtmosphere: true,
        atmosphereThickness: 0.032,
      },
    ],
  },
];

export function getIC1579StarSystemById(systemId: string): StarSystemConfig | undefined {
  return IC1579_STAR_SYSTEMS.find((sys) => sys.id === systemId);
}

export const IC1579_SYSTEM_IDS: string[] = IC1579_STAR_SYSTEMS.map((sys) => sys.id);
