import type { StarSystemConfig } from '../../types/starSystem';

export const PRIME_GALAXY_STAR_SYSTEMS: StarSystemConfig[] = [
  // ==========================================================================
  // STAR SYSTEM 01: BLUE STAR SYSTEM (5 Planets, 1 Earth-like candidate)
  // ==========================================================================
  {
    id: 'system-blue',
    name: 'Aethelis Blue System',
    designation: 'PRIME // STAR SYSTEM 01',
    description: 'A luminous electric-blue O-type main sequence star situated on the inner spiral arm of Aether Prime, harboring 5 diverse worlds.',
    galaxyId: 'galaxy01',
    positionInGalaxy: [-6.8, 0.4, 8.4],
    systemRadius: 7.5,
    star: {
      id: 'star-blue',
      name: 'Aethelis Core',
      spectralType: 'O5-V Blue Supergiant',
      apparentRadius: 0.58,
      coreColor: '#E8F6FF',
      coronaColor: '#00D2FF',
      glowColor: '#1588FF',
      flareColor: '#80E5FF',
      pulseSpeed: 1.4,
      coronaIntensity: 1.8,
      plasmaParticlesCount: 220,
    },
    planets: [
      {
        id: 'blue-p1',
        name: 'Aethel-I (Caelum)',
        type: 'rocky',
        subtitle: 'Scorched Iron World',
        description: 'Tidally locked basalt world with heavy meteorite impact craters and iron dust ridges.',
        radius: 0.048,
        orbitRadius: 1.45,
        orbitSpeed: 1.45,
        orbitEccentricity: 0.08,
        orbitInclination: 0.03,
        orbitPhase: 0.4,
        rotationSpeed: 0.45,
        axialTilt: 0.04,
        primaryColor: '#786C5E',
        secondaryColor: '#3D352E',
        accentColor: '#BFA893',
        hasAtmosphere: false,
      },
      {
        id: 'blue-p2',
        name: 'Aethel-II (Vespera)',
        type: 'hot-lava',
        subtitle: 'Sulfur & Magma World',
        description: 'Superheated silicate planet experiencing intense coronal flare heating, with glowing lava fractures.',
        radius: 0.065,
        orbitRadius: 2.15,
        orbitSpeed: 1.05,
        orbitEccentricity: 0.05,
        orbitInclination: 0.06,
        orbitPhase: 2.1,
        rotationSpeed: 0.35,
        axialTilt: 0.08,
        primaryColor: '#8A2B0E',
        secondaryColor: '#FF6200',
        accentColor: '#FFAE00',
        atmosphereColor: '#FF7B00',
        hasAtmosphere: true,
        atmosphereThickness: 0.015,
      },
      {
        id: 'blue-p3',
        name: 'Aethel-III (Oasis Prime)',
        type: 'earth-like',
        subtitle: 'Earth-like Oceanic World',
        description: 'Temperate oceanic world with extensive cyan-blue hydrosphere, verdant continents, dynamic cloud systems, and a thin protective atmosphere.',
        radius: 0.084,
        orbitRadius: 3.10,
        orbitSpeed: 0.78,
        orbitEccentricity: 0.02,
        orbitInclination: 0.02,
        orbitPhase: 4.3,
        rotationSpeed: 0.28,
        axialTilt: 0.41, // 23.5 degrees
        cloudRotationSpeed: 0.36,
        primaryColor: '#0B5299',
        secondaryColor: '#2D7538',
        accentColor: '#9C7A4A',
        atmosphereColor: '#45B6FE',
        hasAtmosphere: true,
        atmosphereThickness: 0.022,
        hasClouds: true,
      },
      {
        id: 'blue-p4',
        name: 'Aethel-IV (Glaciem)',
        type: 'ice',
        subtitle: 'Sub-Zero Cryo World',
        description: 'Methane and water-ice planet with sprawling crystalline fractures and faint blue nitrogen atmospheric haze.',
        radius: 0.096,
        orbitRadius: 4.40,
        orbitSpeed: 0.58,
        orbitEccentricity: 0.04,
        orbitInclination: 0.05,
        orbitPhase: 1.2,
        rotationSpeed: 0.38,
        axialTilt: 0.16,
        primaryColor: '#82C8E5',
        secondaryColor: '#D8F3FF',
        accentColor: '#30759E',
        atmosphereColor: '#A0E8FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.018,
      },
      {
        id: 'blue-p5',
        name: 'Aethel-V (Zephyrus)',
        type: 'ringed-giant',
        subtitle: 'Azure Ringed Jovian Giant',
        description: 'Colossal gas giant with deep cyan atmospheric jet streams and a majestic, highly reflective icy ring system.',
        radius: 0.145,
        orbitRadius: 5.95,
        orbitSpeed: 0.40,
        orbitEccentricity: 0.03,
        orbitInclination: 0.04,
        orbitPhase: 3.5,
        rotationSpeed: 0.55,
        axialTilt: 0.22,
        primaryColor: '#1A6DBA',
        secondaryColor: '#6BD4FF',
        accentColor: '#0D3E70',
        atmosphereColor: '#70D6FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.035,
        rings: {
          innerRadius: 0.19,
          outerRadius: 0.36,
          color1: '#BFE7FF',
          color2: '#68B0D8',
          opacity: 0.85,
        },
      },
    ],
  },

  // ==========================================================================
  // STAR SYSTEM 02: MASSIVE STAR SYSTEM (10 Planets, 3 Hot, 2 Earth-like, 5 Distinct)
  // ==========================================================================
  {
    id: 'system-massive',
    name: 'Helios Magnitude System',
    designation: 'PRIME // STAR SYSTEM 02',
    description: 'A colossal, highly luminous hypergiant star radiating golden-amber energy, commanding a massive armada of 10 orbiting planetary bodies.',
    galaxyId: 'galaxy01',
    positionInGalaxy: [12.8, 0.8, -10.5],
    systemRadius: 21.0,
    star: {
      id: 'star-massive',
      name: 'Helios Colossus',
      spectralType: 'F0-Ia Yellow-Gold Hypergiant',
      apparentRadius: 1.65, // ~10x visual volume / prominence
      coreColor: '#FFFDF0',
      coronaColor: '#FFB800',
      glowColor: '#FF6D00',
      flareColor: '#FFD700',
      pulseSpeed: 0.85,
      coronaIntensity: 2.2,
      plasmaParticlesCount: 380,
    },
    planets: [
      // 3 Hot Planets
      {
        id: 'massive-p1',
        name: 'Ignis-I (Vulcan)',
        type: 'hot-lava',
        subtitle: 'Magma Ocean Planet',
        description: 'Violent tectonic world constantly resurfaced by boiling magma seas and glowing caldera ridges.',
        radius: 0.072,
        orbitRadius: 3.20,
        orbitSpeed: 1.30,
        orbitEccentricity: 0.06,
        orbitInclination: 0.04,
        orbitPhase: 0.2,
        rotationSpeed: 0.25,
        axialTilt: 0.02,
        primaryColor: '#9E1E05',
        secondaryColor: '#FF3C00',
        accentColor: '#FFD000',
        atmosphereColor: '#FF5100',
        hasAtmosphere: true,
        atmosphereThickness: 0.018,
      },
      {
        id: 'massive-p2',
        name: 'Ignis-II (Tartarus)',
        type: 'hot-lava',
        subtitle: 'Basalt Caldera World',
        description: 'Scorched obsidian crust with glowing orange volcanic fissure networks and sulfur steam plumes.',
        radius: 0.082,
        orbitRadius: 4.45,
        orbitSpeed: 1.05,
        orbitEccentricity: 0.04,
        orbitInclination: 0.05,
        orbitPhase: 2.4,
        rotationSpeed: 0.30,
        axialTilt: 0.06,
        primaryColor: '#4A1208',
        secondaryColor: '#D44A00',
        accentColor: '#FF8800',
        atmosphereColor: '#FF6600',
        hasAtmosphere: true,
        atmosphereThickness: 0.016,
      },
      {
        id: 'massive-p3',
        name: 'Ignis-III (Pyroclast)',
        type: 'hot-lava',
        subtitle: 'Thermal Radiation World',
        description: 'Deep crimson volcanic world bathed in intense solar radiance with incandescent atmospheric hazes.',
        radius: 0.076,
        orbitRadius: 5.70,
        orbitSpeed: 0.88,
        orbitEccentricity: 0.03,
        orbitInclination: 0.02,
        orbitPhase: 5.1,
        rotationSpeed: 0.35,
        axialTilt: 0.05,
        primaryColor: '#6B1B1B',
        secondaryColor: '#FF6020',
        accentColor: '#FFA850',
        atmosphereColor: '#FF7040',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
      },

      // 2 Potentially Habitable / Earth-like Worlds
      {
        id: 'massive-p4',
        name: 'Terran-Alpha (Gaia Nova)',
        type: 'earth-like',
        subtitle: 'Verdant Earth-like Super-World',
        description: 'Expansive azure oceans, lush emerald continents, dynamic polar vortex clouds, and high atmospheric transparency.',
        radius: 0.095,
        orbitRadius: 7.25,
        orbitSpeed: 0.72,
        orbitEccentricity: 0.015,
        orbitInclination: 0.03,
        orbitPhase: 1.8,
        rotationSpeed: 0.28,
        axialTilt: 0.38,
        cloudRotationSpeed: 0.34,
        primaryColor: '#0E62A8',
        secondaryColor: '#2B823E',
        accentColor: '#C49E66',
        atmosphereColor: '#52C1FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.025,
        hasClouds: true,
      },
      {
        id: 'massive-p5',
        name: 'Terran-Beta (Aegis)',
        type: 'earth-like',
        subtitle: 'Cyan Archipelago World',
        description: 'Tropical archipelago super-Earth with extensive shallow turquoise reefs, green island chains, and cyclone cloud formations.',
        radius: 0.105,
        orbitRadius: 10.40,
        orbitSpeed: 0.54,
        orbitEccentricity: 0.025,
        orbitInclination: 0.04,
        orbitPhase: 4.1,
        rotationSpeed: 0.32,
        axialTilt: 0.32,
        cloudRotationSpeed: 0.38,
        primaryColor: '#088099',
        secondaryColor: '#36A360',
        accentColor: '#80B584',
        atmosphereColor: '#64E5FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.024,
        hasClouds: true,
      },

      // 5 Distinct Worlds
      {
        id: 'massive-p6',
        name: 'Glacia (Boreas)',
        type: 'ice',
        subtitle: 'Glacial Nitrogen Ice World',
        description: 'Pure blue-white crystalline ice surface etched by deep cobalt tectonic rifts and frozen geyser plains.',
        radius: 0.082,
        orbitRadius: 8.85,
        orbitSpeed: 0.62,
        orbitEccentricity: 0.05,
        orbitInclination: 0.06,
        orbitPhase: 3.3,
        rotationSpeed: 0.40,
        axialTilt: 0.18,
        primaryColor: '#A2E2F8',
        secondaryColor: '#FFFFFF',
        accentColor: '#4A92B8',
        atmosphereColor: '#C2F0FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.015,
      },
      {
        id: 'massive-p7',
        name: 'Chronos (Aurum)',
        type: 'ringed-giant',
        subtitle: 'Golden Ringed Gas Giant',
        description: 'Enormous amber and gold banded gas giant surrounded by a vast concentric ring system of fine ice-dust crystals.',
        radius: 0.22,
        orbitRadius: 12.40,
        orbitSpeed: 0.44,
        orbitEccentricity: 0.02,
        orbitInclination: 0.03,
        orbitPhase: 0.9,
        rotationSpeed: 0.65,
        axialTilt: 0.48,
        primaryColor: '#CC8800',
        secondaryColor: '#FFE082',
        accentColor: '#8C5500',
        atmosphereColor: '#FFD54F',
        hasAtmosphere: true,
        atmosphereThickness: 0.045,
        rings: {
          innerRadius: 0.28,
          outerRadius: 0.54,
          color1: '#FFE57F',
          color2: '#FFA000',
          opacity: 0.88,
        },
      },
      {
        id: 'massive-p8',
        name: 'Noctis (Erebos)',
        type: 'dark-banded',
        subtitle: 'Obsidian Bioluminescent World',
        description: 'Mysterious ultra-dark world with low reflectivity, illuminated by iridescent electric plasma bands in its upper stratosphere.',
        radius: 0.11,
        orbitRadius: 14.70,
        orbitSpeed: 0.36,
        orbitEccentricity: 0.04,
        orbitInclination: 0.08,
        orbitPhase: 5.6,
        rotationSpeed: 0.25,
        axialTilt: 0.12,
        primaryColor: '#12121A',
        secondaryColor: '#281E38',
        accentColor: '#9C27B0',
        atmosphereColor: '#BA68C8',
        hasAtmosphere: true,
        atmosphereThickness: 0.028,
      },
      {
        id: 'massive-p9',
        name: 'Thalassa (Oceanus)',
        type: 'ocean',
        subtitle: 'Pure Pelagic Ocean World',
        description: 'Complete 100% deep water mantle with no exposed landmass, exhibiting specular solar reflections and spiraling white cirrus storms.',
        radius: 0.098,
        orbitRadius: 17.20,
        orbitSpeed: 0.28,
        orbitEccentricity: 0.015,
        orbitInclination: 0.04,
        orbitPhase: 2.7,
        rotationSpeed: 0.30,
        axialTilt: 0.26,
        cloudRotationSpeed: 0.35,
        primaryColor: '#05386B',
        secondaryColor: '#106BA8',
        accentColor: '#5CDB95',
        atmosphereColor: '#38A3A5',
        hasAtmosphere: true,
        atmosphereThickness: 0.022,
        hasClouds: true,
      },
      {
        id: 'massive-p10',
        name: 'Aura (Prisma)',
        type: 'dense-atmosphere',
        subtitle: 'Chromatic Cloud Giant',
        description: 'Exotic high-pressure world enveloped by shifting magenta, violet, and teal aerosol layers with chromatic gradient storms.',
        radius: 0.13,
        orbitRadius: 19.90,
        orbitSpeed: 0.22,
        orbitEccentricity: 0.03,
        orbitInclination: 0.05,
        orbitPhase: 4.8,
        rotationSpeed: 0.42,
        axialTilt: 0.34,
        primaryColor: '#6A1B9A',
        secondaryColor: '#00897B',
        accentColor: '#E91E63',
        atmosphereColor: '#80CBC4',
        hasAtmosphere: true,
        atmosphereThickness: 0.032,
      },
    ],
  },

  // ==========================================================================
  // STAR SYSTEM 03: VIOLET STAR SYSTEM (6 Distinct Planets)
  // ==========================================================================
  {
    id: 'system-violet',
    name: 'Astralium Violet System',
    designation: 'PRIME // STAR SYSTEM 03',
    description: 'An exotic white-hot core surrounded by an energetic magenta-violet coronal halo on the secondary spiral arm, anchoring 6 distinct planetary bodies.',
    galaxyId: 'galaxy01',
    positionInGalaxy: [-11.5, -0.6, -8.2],
    systemRadius: 8.5,
    star: {
      id: 'star-violet',
      name: 'Astralium Core',
      spectralType: 'B2-V Violet Subdwarf',
      apparentRadius: 0.65,
      coreColor: '#FAF0FF',
      coronaColor: '#D500F9',
      glowColor: '#7C4DFF',
      flareColor: '#EA80FC',
      pulseSpeed: 1.25,
      coronaIntensity: 1.9,
      plasmaParticlesCount: 260,
    },
    planets: [
      {
        id: 'violet-p1',
        name: 'Nyx-I (Obsidia)',
        type: 'hot-lava',
        subtitle: 'Violet Fissure World',
        description: 'High-density mineral planet with glowing ultraviolet volcanic rifts and black metallic sands.',
        radius: 0.052,
        orbitRadius: 1.60,
        orbitSpeed: 1.35,
        orbitEccentricity: 0.06,
        orbitInclination: 0.04,
        orbitPhase: 0.5,
        rotationSpeed: 0.30,
        axialTilt: 0.04,
        primaryColor: '#21092B',
        secondaryColor: '#B0006D',
        accentColor: '#FF4081',
        atmosphereColor: '#E040FB',
        hasAtmosphere: true,
        atmosphereThickness: 0.014,
      },
      {
        id: 'violet-p2',
        name: 'Nyx-II (Krypton)',
        type: 'rocky',
        subtitle: 'Violet-Tinted Silicate World',
        description: 'Cratered rocky terrain composed of quartz and amethyst crystal geological formations.',
        radius: 0.065,
        orbitRadius: 2.45,
        orbitSpeed: 1.05,
        orbitEccentricity: 0.04,
        orbitInclination: 0.06,
        orbitPhase: 2.2,
        rotationSpeed: 0.38,
        axialTilt: 0.12,
        primaryColor: '#5C4A6B',
        secondaryColor: '#31223D',
        accentColor: '#9C82B3',
        hasAtmosphere: false,
      },
      {
        id: 'violet-p3',
        name: 'Nyx-III (Indigo Deep)',
        type: 'ocean',
        subtitle: 'Deep Indigo Ocean World',
        description: 'Ultramarine ocean mantle enriched with bioluminescent microorganisms beneath thin purple atmospheric mists.',
        radius: 0.086,
        orbitRadius: 3.40,
        orbitSpeed: 0.82,
        orbitEccentricity: 0.02,
        orbitInclination: 0.03,
        orbitPhase: 4.6,
        rotationSpeed: 0.32,
        axialTilt: 0.28,
        cloudRotationSpeed: 0.36,
        primaryColor: '#1A237E',
        secondaryColor: '#283593',
        accentColor: '#7C4DFF',
        atmosphereColor: '#B388FF',
        hasAtmosphere: true,
        atmosphereThickness: 0.022,
        hasClouds: true,
      },
      {
        id: 'violet-p4',
        name: 'Nyx-IV (Nebularis)',
        type: 'gas-giant',
        subtitle: 'Turbulent Magenta Gas Giant',
        description: 'Vast swirling planetary body with alternating bands of deep violet, magenta, and white hydrogen clouds.',
        radius: 0.155,
        orbitRadius: 4.65,
        orbitSpeed: 0.64,
        orbitEccentricity: 0.03,
        orbitInclination: 0.05,
        orbitPhase: 1.4,
        rotationSpeed: 0.58,
        axialTilt: 0.35,
        primaryColor: '#4A148C',
        secondaryColor: '#AA00FF',
        accentColor: '#E1BEE7',
        atmosphereColor: '#EA80FC',
        hasAtmosphere: true,
        atmosphereThickness: 0.038,
      },
      {
        id: 'violet-p5',
        name: 'Nyx-V (Lumina)',
        type: 'ringed-giant',
        subtitle: 'Silver-Violet Ringed Sovereign',
        description: 'Magnificent silver and lavender gas giant crowned by wide, illuminated crystalline ring arcs.',
        radius: 0.135,
        orbitRadius: 6.05,
        orbitSpeed: 0.50,
        orbitEccentricity: 0.02,
        orbitInclination: 0.04,
        orbitPhase: 3.8,
        rotationSpeed: 0.48,
        axialTilt: 0.42,
        primaryColor: '#7E57C2',
        secondaryColor: '#D1C4E9',
        accentColor: '#512DA8',
        atmosphereColor: '#EDE7F6',
        hasAtmosphere: true,
        atmosphereThickness: 0.032,
        rings: {
          innerRadius: 0.18,
          outerRadius: 0.35,
          color1: '#EDE7F6',
          color2: '#B39DDB',
          opacity: 0.82,
        },
      },
      {
        id: 'violet-p6',
        name: 'Nyx-VI (Cocytus)',
        type: 'ice',
        subtitle: 'Outer Methane Ice Sentinel',
        description: 'Distant frozen planet consisting of deep nitrogen-methane glacial sheets under permanent sub-zero night.',
        radius: 0.075,
        orbitRadius: 7.55,
        orbitSpeed: 0.38,
        orbitEccentricity: 0.05,
        orbitInclination: 0.07,
        orbitPhase: 5.9,
        rotationSpeed: 0.35,
        axialTilt: 0.15,
        primaryColor: '#90CAF9',
        secondaryColor: '#E3F2FD',
        accentColor: '#42A5F5',
        atmosphereColor: '#BBDEFB',
        hasAtmosphere: true,
        atmosphereThickness: 0.015,
      },
    ],
  },

  // ==========================================================================
  // STAR SYSTEM 04: MULTI-EARTH SYSTEM (7 Planets, 2 Earth-like worlds)
  // ==========================================================================
  {
    id: 'system-multi-earth',
    name: 'Solaria Twin-Earth System',
    designation: 'PRIME // STAR SYSTEM 04',
    description: 'A stable G-type solar analog residing in a dense star-forming cradle of Aether Prime, harboring two extraordinary Earth-like sister worlds.',
    galaxyId: 'galaxy01',
    positionInGalaxy: [8.2, 0.3, 11.8],
    systemRadius: 10.5,
    star: {
      id: 'star-multi-earth',
      name: 'Solaria Prime',
      spectralType: 'G2-V Golden Sun',
      apparentRadius: 0.72,
      coreColor: '#FFFEEA',
      coronaColor: '#FFD700',
      glowColor: '#FFA500',
      flareColor: '#FFE082',
      pulseSpeed: 1.1,
      coronaIntensity: 1.7,
      plasmaParticlesCount: 240,
    },
    planets: [
      {
        id: 'sol-p1',
        name: 'Sol-A (Hermes)',
        type: 'rocky',
        subtitle: 'Baked Silicate World',
        description: 'Heavily cratered, sun-scorched rocky planet with extreme temperature differentials.',
        radius: 0.048,
        orbitRadius: 1.55,
        orbitSpeed: 1.30,
        orbitEccentricity: 0.08,
        orbitInclination: 0.05,
        orbitPhase: 0.8,
        rotationSpeed: 0.25,
        axialTilt: 0.02,
        primaryColor: '#8D6E63',
        secondaryColor: '#4E342E',
        accentColor: '#D7CCC8',
        hasAtmosphere: false,
      },
      // Earth-like World 1 (Tropical / Warm)
      {
        id: 'sol-p2',
        name: 'Sol-B (Terra Nova)',
        type: 'earth-like',
        subtitle: 'Warm Earth-like Biosphere Analog',
        description: 'Warm temperate world with extensive cyan ocean basins, golden deserts, verdant rainforest continents, and swirling white cloud spirals.',
        radius: 0.082,
        orbitRadius: 2.45,
        orbitSpeed: 0.98,
        orbitEccentricity: 0.02,
        orbitInclination: 0.02,
        orbitPhase: 2.6,
        rotationSpeed: 0.28,
        axialTilt: 0.36, // 21 degrees
        cloudRotationSpeed: 0.34,
        primaryColor: '#0F70B7',
        secondaryColor: '#348E47',
        accentColor: '#D4AC6E',
        atmosphereColor: '#62CDFF',
        hasAtmosphere: true,
        atmosphereThickness: 0.022,
        hasClouds: true,
      },
      {
        id: 'sol-p3',
        name: 'Sol-C (Jupiter Analog)',
        type: 'gas-giant',
        subtitle: 'Banded Jovian Giant',
        description: 'Massive hydrogen gas giant with caramel, amber, and cream cloud belts and violent anticyclonic storms.',
        radius: 0.145,
        orbitRadius: 3.70,
        orbitSpeed: 0.75,
        orbitEccentricity: 0.03,
        orbitInclination: 0.04,
        orbitPhase: 4.8,
        rotationSpeed: 0.62,
        axialTilt: 0.08,
        primaryColor: '#A06D3B',
        secondaryColor: '#F5DEB3',
        accentColor: '#8A4513',
        atmosphereColor: '#FFE4B5',
        hasAtmosphere: true,
        atmosphereThickness: 0.035,
      },
      {
        id: 'sol-p4',
        name: 'Sol-D (Saturn Analog)',
        type: 'ringed-giant',
        subtitle: 'Golden Ringed Giant',
        description: 'Pristine golden-yellow gas giant enveloped by a wide, high-contrast equatorial ring system.',
        radius: 0.125,
        orbitRadius: 5.05,
        orbitSpeed: 0.60,
        orbitEccentricity: 0.02,
        orbitInclination: 0.05,
        orbitPhase: 1.1,
        rotationSpeed: 0.52,
        axialTilt: 0.46,
        primaryColor: '#D4AF37',
        secondaryColor: '#FAF0E6',
        accentColor: '#AA7C11',
        atmosphereColor: '#FFF8DC',
        hasAtmosphere: true,
        atmosphereThickness: 0.032,
        rings: {
          innerRadius: 0.16,
          outerRadius: 0.32,
          color1: '#F5DEB3',
          color2: '#D2B48C',
          opacity: 0.86,
        },
      },
      // Earth-like World 2 (Boreal / Cool)
      {
        id: 'sol-p5',
        name: 'Sol-E (Avalon)',
        type: 'earth-like',
        subtitle: 'Boreal Earth-like Ocean World',
        description: 'Cooler sister Earth-analog featuring deep cobalt oceans, vast pine and taiga continents, twin polar ice caps, and dynamic weather patterns.',
        radius: 0.088,
        orbitRadius: 6.45,
        orbitSpeed: 0.48,
        orbitEccentricity: 0.018,
        orbitInclination: 0.03,
        orbitPhase: 3.4,
        rotationSpeed: 0.30,
        axialTilt: 0.43, // 24.5 degrees
        cloudRotationSpeed: 0.38,
        primaryColor: '#0D4F8B',
        secondaryColor: '#246B48',
        accentColor: '#E0F2F1',
        atmosphereColor: '#4FC3F7',
        hasAtmosphere: true,
        atmosphereThickness: 0.024,
        hasClouds: true,
      },
      {
        id: 'sol-p6',
        name: 'Sol-F (Aeolus)',
        type: 'dense-atmosphere',
        subtitle: 'Amber Atmosphere Planet',
        description: 'Dense, high-pressure world shrouded in radiant amber, gold, and teal swirling aerosol cloud decks.',
        radius: 0.110,
        orbitRadius: 7.95,
        orbitSpeed: 0.38,
        orbitEccentricity: 0.04,
        orbitInclination: 0.06,
        orbitPhase: 5.2,
        rotationSpeed: 0.36,
        axialTilt: 0.25,
        primaryColor: '#E65100',
        secondaryColor: '#FFD54F',
        accentColor: '#00838F',
        atmosphereColor: '#FFE082',
        hasAtmosphere: true,
        atmosphereThickness: 0.028,
      },
      {
        id: 'sol-p7',
        name: 'Sol-G (Hyperborea)',
        type: 'ice',
        subtitle: 'Distant Cryogenic Outpost',
        description: 'Frozen nitrogen world marking the outer boundary of the Solaria planetary system.',
        radius: 0.068,
        orbitRadius: 9.60,
        orbitSpeed: 0.28,
        orbitEccentricity: 0.05,
        orbitInclination: 0.08,
        orbitPhase: 1.9,
        rotationSpeed: 0.34,
        axialTilt: 0.18,
        primaryColor: '#B0BEC5',
        secondaryColor: '#ECEFF1',
        accentColor: '#607D8B',
        atmosphereColor: '#CFD8DC',
        hasAtmosphere: true,
        atmosphereThickness: 0.012,
      },
    ],
  },
];

export function getStarSystemById(systemId: string): StarSystemConfig | undefined {
  return PRIME_GALAXY_STAR_SYSTEMS.find((sys) => sys.id === systemId);
}
